import { legalDocument, legalDocumentHead } from "../../components/legal-document.js";

export function privacyPage() {
  const sections = [
    ["Information We Collect", "InfoBridgeIndia may collect account details such as your name and email address, information you enter into business tools and workspaces, and details you provide through our Contact form. Technical and usage information may include browser and device information, IP addresses and interactions with the website."],
    ["How We Use Information", "We use information to provide and operate InfoBridgeIndia, maintain accounts, deliver requested tool and workspace functionality, and respond to support enquiries. Information may also be used to improve the website, maintain security and meet applicable obligations."],
    ["Business and Workspace Data", "Users may enter business, accounting, GST, inventory, HR, sales and other operational information into the platform. We handle this information to provide the features users request. Users remain responsible for the accuracy of the information they submit and for having an appropriate basis to provide information about customers, employees or other people. Please avoid entering sensitive information that is not needed for your work."],
    ["Contact Form Information", "When you submit the Contact form, your name, email address and message are processed so that we can receive and respond to your enquiry. We use Formspree as our third-party form-processing service. Formspree processes submissions to deliver them to us. Please do not include passwords or unnecessary sensitive business information in your message."],
    ["Cookies, Analytics and Advertising", "The public website uses Google Analytics to help us understand website usage and Google AdSense to support advertising. These services may use cookies or similar technologies and process technical and usage information according to their own policies and applicable settings.", "You can manage cookies through your browser settings. Google explains its practices in <a href=\"https://policies.google.com/technologies/partner-sites\">How Google uses information from sites or apps that use its services</a>. Changing cookie settings may affect some website features."],
    ["Third-Party Services", "InfoBridgeIndia may rely on service providers for hosting, authentication, analytics, advertising, contact forms, storage and other technical functions. These providers may process information needed to perform their services. External services and websites may have their own privacy policies and terms. Information may also be disclosed where required by applicable law."],
    ["Data Security", "We use reasonable technical and organisational measures appropriate to the services we provide to help protect information. No internet-based service or storage method can guarantee absolute security. Users should protect their login credentials and devices and avoid sharing account access."],
    ["Data Retention", "Information is retained as necessary to provide the service, respond to enquiries, maintain legitimate business records or meet applicable requirements. Retention depends on the type of information and the purpose for which it is used. Files you download to your device remain under your control."],
    ["User Choices and Requests", "You may use available account and workspace features to review or update your information. For privacy questions, corrections or deletion requests where applicable, please use our <a href=\"/contact.html\">Contact page</a>. We may need to confirm your identity before acting on a request. Some information may need to be retained to meet applicable requirements."],
    ["Children's Privacy", "The InfoBridgeIndia business platform is not specifically directed to children. If you believe a child has provided personal information that should not have been submitted, please contact us so we can review the matter."],
    ["Changes to this Privacy Policy", "We may update this Privacy Policy when our services, practices or applicable requirements change. The date at the top of this page indicates when it was last updated."],
    ["Contact", "For questions about this Privacy Policy or how InfoBridgeIndia handles information, please use our <a href=\"/contact.html\">Contact page</a>."],
  ];
  return { route: "/privacy.html", title: "Privacy Policy", description: "How InfoBridgeIndia collects, uses and manages information.", active: "", extraHead: legalDocumentHead, body: legalDocument({ title: "Privacy Policy", introduction: "This Privacy Policy explains how InfoBridgeIndia handles information when you use our website, business tools and platform, and how you can contact us about your information.", sections }) };
}

export function termsPage() {
  const sections = [
    ["Acceptance of Terms", "These Terms of Use explain the conditions for accessing and using the InfoBridgeIndia website, business tools and platform. By using the services, you agree to these Terms. If you do not agree, please do not use the services."],
    ["Use of InfoBridgeIndia", "Use InfoBridgeIndia lawfully and responsibly, for the purposes supported by its website, tools and platform. You are responsible for ensuring that your use of the services is appropriate for your needs and complies with applicable requirements."],
    ["User Accounts", "Where an account is required, you are responsible for providing accurate account information and keeping your login access secure. Do not share your credentials with people who are not authorised to access your account. Contact us if you believe your account has been compromised."],
    ["Business Information and User Responsibility", "Our accounting, GST, tax, payroll, inventory and other business tools assist users with their work. You are responsible for the information you enter and for checking calculations, records and generated outputs before relying on them, making business decisions or submitting information to authorities or other parties."],
    ["Acceptable Use", "You must not use the services for illegal or harmful activity, attempt unauthorised access, interfere with the website or other users, or misuse account access. Do not submit information that you are not entitled to provide."],
    ["Availability and Changes to the Service", "Features may be updated, changed or removed as the platform develops. Services may be interrupted by maintenance, technical issues or other circumstances. We do not guarantee uninterrupted or error-free availability."],
    ["Third-Party Services", "Some features rely on third-party services for hosting, authentication, analytics, advertising, contact forms, storage or integrations. Those services may have their own terms and privacy policies, and their availability may affect the features that depend on them."],
    ["Intellectual Property", "InfoBridgeIndia branding, website design and original platform materials are protected by applicable intellectual-property rights. These Terms do not transfer ownership of those materials to users. Users retain responsibility for the business data they provide."],
    ["No Professional Advice", "InfoBridgeIndia provides tools and information to assist with business tasks. It does not replace professional accounting, tax, legal or compliance advice. Seek qualified advice when your circumstances require it."],
    ["Disclaimer and Limitation of Responsibility", "Outputs depend on the information supplied and the capabilities of the tool being used. We do not guarantee that every output will be complete, accurate or suitable for a particular purpose. Users remain responsible for verifying outputs and for business decisions and submissions made using them. Nothing in these Terms excludes responsibilities that cannot be excluded under applicable law."],
    ["Suspension or Termination", "Access may be restricted, suspended or terminated if the service is misused, these Terms are violated, or action is needed to address security risks or applicable requirements."],
    ["Changes to These Terms", "These Terms may be updated when the website, services or applicable requirements change. Please review this page periodically. The date at the top indicates the latest update."],
    ["Contact", "For questions about these Terms, please use our <a href=\"/contact.html\">Contact page</a>."],
  ];
  return { route: "/terms.html", title: "Terms of Use", description: "Terms for accessing and using InfoBridgeIndia and its related services.", active: "", extraHead: legalDocumentHead, body: legalDocument({ title: "Terms of Use", introduction: "These Terms of Use explain the conditions for accessing and using the InfoBridgeIndia website, business tools and platform.", sections }) };
}
