export const STORES=["settings","departments","shifts","employees","attendance","attendanceImports","attendanceMappings","attendanceCorrections","leaveTypes","leaveBalances","leaveTransactions","payrollRuns","payrollAdjustments","payslips"];
export const WEEKDAYS=Object.freeze(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]);
export const weekday=date=>WEEKDAYS[(new Date(`${date}T00:00:00Z`).getUTCDay()+6)%7];
const cleanDays=value=>[...new Set((Array.isArray(value)?value:String(value||"").split(/[,/|]+/)).map(x=>String(x).trim()).filter(x=>WEEKDAYS.includes(x)))];
export function weeklyOffConfig(employee={},settings={}){const fallback=cleanDays(settings.weeklyOffDays?.length?settings.weeklyOffDays:settings.weeklyOff||"Sunday"),days=cleanDays(employee.weeklyOffDays?.length?employee.weeklyOffDays:fallback.length?fallback:["Sunday"]),type=employee.weeklyOffType||(days.length===1?"one":days.length===2?"two":"custom");return{type,days}}
export function validateWeeklyOff(type,days){const selected=cleanDays(days),errors=[];if(!["one","two","custom"].includes(type))errors.push("Select a weekly-off type.");if(!selected.length)errors.push("Select at least one weekly-off day.");if(type==="one"&&selected.length!==1)errors.push("One day per week requires exactly 1 weekday.");if(type==="two"&&selected.length!==2)errors.push("Two days per week requires exactly 2 weekdays.");return{valid:errors.length===0,errors,days:selected}}
export function periodCalendar(from,to,employee={},settings={}){const config=weeklyOffConfig(employee,settings),calendarDates=[];for(let d=new Date(`${from}T00:00:00Z`),end=new Date(`${to}T00:00:00Z`);d<=end;d.setUTCDate(d.getUTCDate()+1))calendarDates.push(d.toISOString().slice(0,10));const weeklyOffDates=calendarDates.filter(day=>config.days.includes(weekday(day))),workingDates=calendarDates.filter(day=>!config.days.includes(weekday(day)));return{calendarDates,weeklyOffDates,workingDates,weeklyOffConfig:config}}
export function monthPeriod(value){const match=/^(\d{4})-(\d{2})$/.exec(String(value||""));if(!match)throw Error("Select a valid attendance month");const year=Number(match[1]),month=Number(match[2]);if(month<1||month>12)throw Error("Select a valid attendance month");const lastDay=new Date(Date.UTC(year,month,0)).getUTCDate();return{from:`${match[1]}-${match[2]}-01`,to:`${match[1]}-${match[2]}-${String(lastDay).padStart(2,"0")}`}}
export const uid=(p="ID")=>`${p}-${Date.now().toString(36).toUpperCase()}-${(crypto.randomUUID?.()||Math.random().toString(36)).slice(0,8).toUpperCase()}`;
export const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(n||0));
export function parseTime(v){if(!/^\d{1,2}:\d{2}$/.test(v||""))return null;const[h,m]=v.split(":").map(Number);return h<24&&m<60?h*60+m:null}
export function attendanceFacts(row,settings={}){const start=parseTime(row.checkIn),end=parseTime(row.checkOut),explicitOt=Number(row.overtimeHours);if(start==null||end==null)return{hours:0,lateMinutes:0,earlyMinutes:0,overtimeHours:Number.isFinite(explicitOt)?Math.max(0,explicitOt):0};const shiftStart=parseTime(settings.shiftStart||"09:30")??570,shiftEnd=parseTime(settings.shiftEnd||"18:00")??1080,breakMinutes=Math.max(0,Number(row.breakHours||0)*60),mins=Math.max(0,end-start-breakMinutes),grace=Number(settings.graceMinutes||0),calculated=Math.max(0,mins-Number(settings.standardHours||8)*60)/60;return{hours:+(mins/60).toFixed(2),lateMinutes:Math.max(0,start-shiftStart-grace),earlyMinutes:Math.max(0,shiftEnd-end),overtimeHours:+(Number.isFinite(explicitOt)?Math.max(0,explicitOt):calculated).toFixed(2)}}
export function validateAttendance(row,{employees=[],attendance=[],leaves=[],settings={},batch=[]}={}){const errors=[],warnings=[],status=String(row.status||"present").toLowerCase(),noTimes=["absent","lop","paid-leave","leave","holiday","week-off"].includes(status),emp=employees.find(e=>e.employeeId===row.employeeId||e.id===row.employeeId);if(!row.employeeId)errors.push("Employee ID is required");else if(!emp)errors.push("Unknown employee");else if(emp.active===false)errors.push("Inactive employee");if(!/^\d{4}-\d{2}-\d{2}$/.test(row.date||""))errors.push("Invalid date");if(!["present","remote","half-day","absent","lop","paid-leave","leave","holiday","week-off"].includes(status))errors.push("Invalid status");const a=parseTime(row.checkIn),b=parseTime(row.checkOut);if(!noTimes&&a==null)errors.push("Invalid check-in");if(!noTimes&&b==null)errors.push("Invalid check-out");if(a!=null&&b!=null&&b<=a)errors.push("Check-out must be after check-in");const employeeId=emp?.id||row.employeeId;if(attendance.some(x=>x.employeeId===employeeId&&x.date===row.date)||batch.some(x=>x.employeeId===employeeId&&x.date===row.date))errors.push("Duplicate attendance for employee and date");if(leaves.some(x=>x.employeeId===employeeId&&x.status==="approved"&&row.date>=x.from&&row.date<=x.to)&&!["paid-leave","leave"].includes(status))errors.push("Conflicts with approved leave");const weeklyOffWork=!!emp&&periodCalendar(row.date,row.date,emp,settings).weeklyOffDates.length>0&&["present","remote","half-day"].includes(status);if(weeklyOffWork)warnings.push("Weekly-off work");const facts={...attendanceFacts(row,settings),weeklyOffWork};if(facts.hours>16)warnings.push("Unusually long work duration");if(facts.lateMinutes)warnings.push(`Late by ${facts.lateMinutes} min`);if(facts.earlyMinutes)warnings.push(`Early departure by ${facts.earlyMinutes} min`);return{employee:emp,errors,warnings,facts,valid:errors.length===0}}
export function workingDates(from,to,employee={},settings={}){return periodCalendar(from,to,employee,settings).workingDates}
export function attendanceBelongsToEmployee(row,employee){const link=String(row?.employeeId||"").trim().toLowerCase(),code=String(row?.employeeCode||"").trim().toLowerCase();return link===String(employee?.id||"").trim().toLowerCase()||link===String(employee?.employeeId||"").trim().toLowerCase()||code===String(employee?.employeeId||"").trim().toLowerCase()}
export function attendanceSummary(employee,{attendance=[],leaves=[],settings={},from,to}={}){const period=periodCalendar(from,to,employee,settings),dateSet=new Set(period.workingDates),weeklySet=new Set(period.weeklyOffDates),rowsByDate=new Map();for(const row of attendance)if(attendanceBelongsToEmployee(row,employee)&&row.date>=from&&row.date<=to)rowsByDate.set(row.date,row);const rows=[...rowsByDate.values()],approved=leaves.filter(l=>(l.employeeId===employee.id||String(l.employeeId).toLowerCase()===String(employee.employeeId).toLowerCase())&&l.status==="approved"&&l.from<=to&&l.to>=from),leaveDates=new Map(),breakdown=new Map();for(const leave of approved)for(const day of period.workingDates)if(day>=leave.from&&day<=leave.to){leaveDates.set(day,leave);const name=leave.leaveTypeName||"Leave";breakdown.set(name,(breakdown.get(name)||0)+1)}let present=0,paidLeave=0,unpaidLeave=0,lop=0,weeklyOffWorked=0,workedHours=0,overtimeHours=0;for(const row of rows){const status=String(row.status||"").toLowerCase();if(weeklySet.has(row.date)){if(["present","remote"].includes(status))weeklyOffWorked+=1;else if(status==="half-day")weeklyOffWorked+=.5;workedHours+=Number(row.hours||0);overtimeHours+=Number(row.overtimeHours||0);continue}if(!dateSet.has(row.date))continue;if(["present","remote"].includes(status))present+=1;else if(status==="half-day"){present+=.5;lop+=.5}else if(["paid-leave","leave","holiday","week-off"].includes(status))paidLeave+=1;else if(["absent","lop"].includes(status))lop+=1;workedHours+=Number(row.hours||0);overtimeHours+=Number(row.overtimeHours||0)}for(const day of period.workingDates)if(!rows.some(a=>a.date===day)&&leaveDates.has(day)){leaveDates.get(day).paid!==false?paidLeave+=1:(unpaidLeave+=1,lop+=1)}const covered=present+paidLeave+lop,missingDays=Math.max(0,period.workingDates.length-covered),payableDays=Math.max(0,period.workingDates.length-lop-missingDays);return{calendarDays:period.calendarDates.length,weeklyOffDays:period.weeklyOffDates.length,workingDays:period.workingDates.length,presentDays:present,paidLeaveDays:paidLeave,unpaidLeaveDays:unpaidLeave,leaveBreakdown:Object.fromEntries(breakdown),lopDays:lop,weeklyOffWorkedDays:weeklyOffWorked,missingDays,workedHours:+workedHours.toFixed(2),overtimeHours:+overtimeHours.toFixed(2),payableDays,weeklyOffConfig:period.weeklyOffConfig}}
// Per-day breakdown for one employee's month, used by the Attendance detail view. Applies
// the exact same weekly-off / existing-record / approved-leave / missing classification
// rules as attendanceSummary above (so the two always agree), but as an independent,
// additive function -- attendanceSummary itself (payroll-critical) is never touched.
export function attendanceMonthDetail(employee,{attendance=[],leaves=[],settings={},from,to}={}){
  const period=periodCalendar(from,to,employee,settings),weeklySet=new Set(period.weeklyOffDates),workingSet=new Set(period.workingDates);
  const rowsByDate=new Map();
  for(const row of attendance)if(attendanceBelongsToEmployee(row,employee)&&row.date>=from&&row.date<=to)rowsByDate.set(row.date,row);
  const approved=leaves.filter(l=>(l.employeeId===employee.id||String(l.employeeId).toLowerCase()===String(employee.employeeId||"").toLowerCase())&&l.status==="approved"&&l.from<=to&&l.to>=from);
  const leaveByDate=new Map();
  for(const leave of approved)for(const day of period.workingDates)if(day>=leave.from&&day<=leave.to)leaveByDate.set(day,leave);
  return period.calendarDates.map(date=>{
    const row=rowsByDate.get(date),isWeeklyOff=weeklySet.has(date),leave=leaveByDate.get(date);
    let status,source;
    if(row){status=String(row.status||"").toLowerCase();source="record"}
    else if(isWeeklyOff){status="week-off";source="weekly-off"}
    else if(leave){status=leave.paid!==false?"paid-leave":"absent";source="leave"}
    else if(workingSet.has(date)){status="missing";source="missing"}
    else{status="week-off";source="weekly-off"}
    return{date,weekday:weekday(date),isWeeklyOff,status,source,recordId:row?.id||null,checkIn:row?.checkIn||"",checkOut:row?.checkOut||"",breakHours:row?.breakHours??"",hours:row?.hours??"",overtimeHours:row?.overtimeHours??"",remarks:row?.remarks||""};
  });
}
export function payrollForEmployee(employee,{attendance=[],leaves=[],adjustments=[],settings={},from,to}={}){const summary=attendanceSummary(employee,{attendance,leaves,settings,from,to}),base=Number(employee.basicSalary||0),allowances=Number(employee.allowances||0),fixedDeductions=Number(employee.deductions||0),overtimeRate=Number(employee.overtimeRate||settings.overtimeRate||0),rate=summary.workingDays?base/summary.workingDays:0,earnedBasic=base,lopDeduction=rate*summary.lopDays,otPay=summary.overtimeHours*overtimeRate,adds=adjustments.filter(a=>a.employeeId===employee.id&&a.type==="earning").reduce((s,a)=>s+Number(a.amount),0),deducts=adjustments.filter(a=>a.employeeId===employee.id&&a.type==="deduction").reduce((s,a)=>s+Number(a.amount),0),deductions=fixedDeductions+deducts,net=earnedBasic+allowances+otPay+adds-deductions-lopDeduction;return{employeeId:employee.id,employeeCode:employee.employeeId,name:`${employee.firstName} ${employee.lastName}`,basic:base,perDay:+rate.toFixed(2),...summary,weeklyOffSnapshot:{type:summary.weeklyOffConfig.type,days:[...summary.weeklyOffConfig.days]},earnedBasic:+earnedBasic.toFixed(2),allowances,otPay:+otPay.toFixed(2),overtime:+otPay.toFixed(2),adjustments:adds,deductions:+deductions.toFixed(2),lopDeduction:+lopDeduction.toFixed(2),gross:+(earnedBasic+allowances+otPay+adds).toFixed(2),net:+net.toFixed(2),issues:[...(summary.missingDays?[`${summary.missingDays} attendance day(s) missing`]:[]),...(!base?["Basic salary is missing"]:[]),...(summary.overtimeHours&&!overtimeRate?["Overtime rate is missing"]:[])]}}
export function csvEscape(v){const s=String(v??"");return /[",\n]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
export function toCsv(rows,cols){return[cols.join(","),...rows.map(r=>cols.map(c=>csvEscape(r[c])).join(","))].join("\n")}
export function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);const headers=(rows.shift()||[]).map(x=>x.trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||"").trim()]))) }
