import { ageing, aggregate, executive, filterRows, num, round, sum } from "./core.js";
import { resolveCountryConfig } from "../country/registry.js";
import { BRANDED_DOCUMENT_BASE_CSS, escapeExportHtml, renderCompanyIdentity, renderInfoBridgeFooter } from "../export/document.js";
import { brandedTemplateSheet, brandedWorkbook, countryCurrencyFormat } from "../export/workbook.js";

const metric = (label, value, note = "", type = "currency") => ({ label, value, note, type });
const section = (title, columns, rows, currencyColumns = [], percentageColumns = []) => ({ title, columns, rows, currencyColumns, percentageColumns });
const labelKey = value => String(value || "").replace(/([a-z0-9])([A-Z])/g, "$1 $2").replace(/[_-]+/g, " ").replace(/\b\w/g, letter => letter.toUpperCase());
const safeRows = rows => Array.isArray(rows) ? rows : [];

function grouped(rows, group, amount) {
  return aggregate(rows, group, amount).map(item => [item.label, item.value, item.records]);
}

export function analyticsReportModel(key, { sources = {}, filters = {}, audit = {}, company = {}, custom = {} } = {}) {
  const config = resolveCountryConfig(company), currency = config.currency, exec = executive(sources, filters);
  const base = { key, title: labelKey(key), currency, country: config.country, period: `${filters.start || "All dates"} to ${filters.end || "Current"}`, metrics: [], sections: [], notes: [], recordCount: 0 };
  if (key === "executive") return { ...base, title: "Executive Dashboard", metrics: [
    metric("Total Sales", exec.sales, "Confirmed invoice gross value less credit notes"), metric("Total Purchases", exec.purchases, "Posted supplier bills less debit notes"),
    metric("Gross Profit", exec.grossProfit, "Net revenue less movement-based COGS"), metric("Net Profit", exec.netProfit, "Requires complete Finance ledger and expenses"),
    metric("Cash & Bank", exec.cashBank, "Signed, non-reversed banking transactions"), metric("Customer Outstanding", exec.receivables),
    metric("Supplier Outstanding", exec.payables), metric("Inventory Value", exec.inventoryValue),
  ], sections: [section("Business Summary", ["Measure", "Amount"], [["Sales", exec.sales], ["Purchases", exec.purchases], ["Receivables", exec.receivables], ["Payables", exec.payables]], ["Amount"])], notes: exec.limitations, recordCount: 1 };
  if (key === "sales") { const rows = filterRows(safeRows(sources.sales?.invoices), filters), credits = filterRows(safeRows(sources.sales?.creditNotes), filters), leads = filterRows(safeRows(sources.sales?.leads), filters), gross = sum(rows, item => item.grandTotal || item.total || item.invoiceValue), returns = sum(credits, item => item.grandTotal || item.total || item.amount), won = leads.filter(item => /won|converted/i.test(item.status)).length; return { ...base, title: "Sales Analytics", metrics: [metric("Gross Invoice Value", gross), metric("Returns", returns), metric("Net Sales", round(gross - returns)), metric("Outstanding", sum(rows, "balanceDue")), metric("Collected", sum(rows, "amountPaid")), metric("Average Order Value", rows.length ? round(gross / rows.length) : 0), metric("Lead Conversion", leads.length ? round(won / leads.length * 100) : null, "Converted leads divided by total leads", "percentage"), metric("Invoices", rows.length, "Included invoice record count", "number")], sections: [section("Customer-wise Sales", ["Customer", "Amount", "Records"], grouped(rows, "customerId", item => item.grandTotal || item.total), ["Amount"])], recordCount: rows.length } }
  if (key === "purchases" || key === "purchase") { const rows = filterRows(safeRows(sources.purchases?.bills), filters), returns = filterRows(safeRows(sources.purchases?.debitNotes), filters), orders = filterRows(safeRows(sources.purchases?.orders), filters); return { ...base, key: "purchases", title: "Purchase Analytics", metrics: [metric("Purchase Value", sum(rows, item => item.grandTotal || item.total)), metric("Purchase Returns", sum(returns, item => item.grandTotal || item.total || item.amount)), metric("Supplier Outstanding", sum(rows, "balanceDue")), metric("Purchase Orders", orders.length, "Non-draft/non-cancelled orders", "number")], sections: [section("Supplier-wise Purchases", ["Supplier", "Amount", "Records"], grouped(rows, "supplierId", item => item.grandTotal || item.total), ["Amount"])], recordCount: rows.length } }
  if (key === "inventory") { const products = safeRows(sources.inventory?.products), moves = filterRows(safeRows(sources.inventory?.movements), filters), missing = products.filter(item => !num(item.costPrice || item.averageCost)), low = products.filter(item => num(item.currentStock || item.stock) <= num(item.reorderLevel || item.minimumStock)); return { ...base, title: "Inventory Analytics", metrics: [metric("Products", products.length, "Active product count", "number"), metric("Stock Value", missing.length ? null : sum(products, item => num(item.currentStock || item.stock) * num(item.costPrice || item.averageCost))), metric("Low / Reorder", low.length, "Stock at or below reorder level", "number"), metric("Movements", moves.length, "Movement records in selected period", "number")], sections: [section("Warehouse-wise Movements", ["Warehouse", "Quantity", "Records"], grouped(moves, "warehouseId", "quantity"))], notes: missing.length ? [`${missing.length} product(s) lack usable cost; stock value remains unavailable.`] : [], recordCount: products.length } }
  if (key === "banking") { const rows = filterRows(safeRows(sources.banking?.transactions), filters), incoming = rows.filter(item => item.direction === "In"), outgoing = rows.filter(item => item.direction === "Out"), unreconciled = rows.filter(item => item.reconciliationStatus !== "Reconciled"); return { ...base, title: "Banking & Cash", metrics: [metric("Book Balance", sum(rows, "signedAmount")), metric("Money In", sum(incoming, "amount")), metric("Money Out", sum(outgoing, "amount")), metric("Unreconciled", sum(unreconciled, "amount"))], sections: [section("Account Movement", ["Account", "Amount", "Records"], grouped(rows, "accountId", "signedAmount"), ["Amount"])], recordCount: rows.length } }
  if (key === "profitability") return { ...base, title: "Profitability", metrics: [metric("Revenue", exec.sales), metric("Sales Returns", exec.salesReturns), metric("Gross Profit", exec.grossProfit), metric("Net Profit", exec.netProfit)], notes: exec.limitations, recordCount: safeRows(sources.sales?.invoices).length };
  if (key === "receivables" || key === "payables") { const receivable = key === "receivables", rows = filterRows(receivable ? safeRows(sources.sales?.invoices) : safeRows(sources.purchases?.bills), filters), aged = ageing(rows), details = aged.details; return { ...base, title: receivable ? "Receivables" : "Payables", metrics: [metric(`Total ${receivable ? "Receivables" : "Payables"}`, sum(details, "balanceDue")), metric("Current / Not Due", aged.buckets.current), metric("0–30 Days", aged.buckets["0-30"]), metric("Above 90 Days", aged.buckets["90+"])], sections: [section("Ageing Details", ["Document", "Due Date", "Outstanding", "Ageing"], details.map(item => [item.invoiceNumber || item.billNumber || item.id, item.analyticsDueDate, item.balanceDue, item.ageingBucket]), ["Outstanding"])], recordCount: details.length } }
  if (key === "statutory" || key === "tax") { const data = sources.statutory || sources.gst || {}, rows = filterRows(safeRows(data.rows), filters).filter(item => !item.excluded), ae = data.taxSystem === "VAT" || config.country === "AE"; const metrics = ae ? [metric("Output Taxable", sum(rows.filter(item => item.direction === "Output"), "taxableValue")), metric("Output VAT", sum(rows.filter(item => item.direction === "Output"), "vat")), metric("Input Taxable", sum(rows.filter(item => item.direction === "Input"), "taxableValue")), metric("Input VAT", sum(rows.filter(item => item.direction === "Input"), "vat")), metric("Net VAT", round(num(data.outputVat) - num(data.inputVat)))] : [metric("Outward Taxable", sum(rows, "taxableValue")), metric("CGST", sum(rows, "cgst")), metric("SGST", sum(rows, "sgst")), metric("IGST", sum(rows, "igst")), metric("Cess", sum(rows, "cess"))]; return { ...base, title: ae ? "VAT & Statutory" : "GST & Statutory", metrics, notes: data.disclaimer ? [data.disclaimer] : [], recordCount: rows.length } }
  if (key === "management") return { ...base, title: "Management Reports", metrics: analyticsReportModel("executive", { sources, filters, audit, company }).metrics, notes: exec.limitations, recordCount: 1 };
  if (key === "audit") { const rows = safeRows(audit.rows); return { ...base, title: "Audit Reports", sections: [section("Audit Trail", ["Time", "Module", "Action", "Record", "Actor", "Reason"], rows.map(item => [item.timestamp || item.createdAt, item.module, item.action, item.recordId || item.id, item.actor || "Current account", item.reason || item.comment || "—"]))], recordCount: rows.length } }
  if (key === "custom") { const rows = safeRows(custom.rows), fields = custom.fields?.length ? custom.fields : Object.keys(rows[0] || {}); return { ...base, title: custom.title || "Custom Report Builder", sections: rows.length ? [section(custom.source || "Custom Report", fields.map(labelKey), rows.map(item => fields.map(field => item[field])))] : [], recordCount: rows.length } }
  if (key === "saved") { const rows = safeRows(custom.savedReports).filter(item => !item.archived); return { ...base, title: "Saved Reports", sections: [section("Saved Report Definitions", ["Name", "Source", "Fields", "Display", "Updated"], rows.map(item => [item.name, item.dataSource, safeRows(item.fields).map(labelKey).join(", "), item.visualisation, item.updatedAt]))], recordCount: rows.length } }
  return base;
}

export function analyticsReportCsv(model) {
  const quote = value => `"${String(value ?? "").replaceAll('"', '""')}"`, lines = [["InfoBridgeIndia"], [model.title], [`Company Currency`, model.currency], ["Reporting Period", model.period], []];
  if (model.metrics.length) lines.push(["Summary Metrics"], ["Metric", "Value", "Notes"], ...model.metrics.map(item => [item.label, item.value ?? "Data not available", item.note]), []);
  for (const item of model.sections) lines.push([item.title], item.columns, ...item.rows, []);
  if (model.notes.length) lines.push(["Notes"], ...model.notes.map(note => [note]));
  return lines.map(row => row.map(quote).join(",")).join("\r\n");
}

export function buildAnalyticsWorkbook(XLSX, model, { company = {}, generatedAt = new Date() } = {}) {
  const detail = `InfoBridgeIndia — Reporting period: ${model.period} — Generated: ${generatedAt.toLocaleString("en-GB")} — Currency: ${model.currency}`;
  const summaryRows = model.metrics.length ? model.metrics.map(item => [item.label, item.type === "percentage" && typeof item.value === "number" ? item.value / 100 : item.value ?? "Data not available", item.note]) : [["Records", model.recordCount, ""]];
  const { book, sheet } = brandedWorkbook(XLSX, { company, country: model.country, title: model.title, headers: ["Metric", "Value", "Notes"], rows: summaryRows, instructions: detail, sheetName: "Summary" });
  model.metrics.forEach((item, index) => { const cell = sheet[XLSX.utils.encode_cell({ r: index + 5, c: 1 })]; if (!cell || typeof cell.v !== "number") return; cell.z = item.type === "currency" ? countryCurrencyFormat(model.country) : item.type === "percentage" ? "0.00%" : "0"; });
  for (const item of model.sections) {
    const reportSheet = brandedTemplateSheet(XLSX, { company, country: model.country, title: item.title, headers: item.columns, rows: item.rows, instructions: detail, currencyColumns: item.currencyColumns });
    for (const name of item.percentageColumns) { const column = item.columns.indexOf(name); if (column < 0) continue; for (let row = 5; row < item.rows.length + 5; row += 1) { const cell = reportSheet[XLSX.utils.encode_cell({ r: row, c: column })]; if (cell && typeof cell.v === "number") { cell.v /= 100; cell.z = "0.00%"; } } }
    XLSX.utils.book_append_sheet(book, reportSheet, item.title.slice(0, 31));
  }
  return book;
}

export function renderAnalyticsPrintDocument(model, { company = {}, generatedAt = new Date() } = {}) {
  const esc = escapeExportHtml, money = new Intl.NumberFormat(resolveCountryConfig(company).defaults.locale, { style: "currency", currency: model.currency, minimumFractionDigits: 2, maximumFractionDigits: 2 }), value = item => item.value === null || item.value === undefined ? "Data not available" : item.type === "percentage" ? `${item.value}%` : item.type === "currency" ? money.format(item.value) : String(item.value);
  const metrics = model.metrics.length ? `<section class="metrics">${model.metrics.map(item => `<article><span>${esc(item.label)}</span><strong>${esc(value(item))}</strong>${item.note ? `<small>${esc(item.note)}</small>` : ""}</article>`).join("")}</section>` : "";
  const sections = model.sections.map(item => `<section class="report-section"><h2>${esc(item.title)}</h2><table><thead><tr>${item.columns.map(column => `<th>${esc(column)}</th>`).join("")}</tr></thead><tbody>${item.rows.map(row => `<tr>${row.map((cell, index) => `<td>${esc(item.currencyColumns.includes(item.columns[index]) && typeof cell === "number" ? money.format(cell) : item.percentageColumns.includes(item.columns[index]) && typeof cell === "number" ? `${cell}%` : cell)}</td>`).join("")}</tr>`).join("")}</tbody></table></section>`).join("");
  const notes = model.notes.length ? `<section class="notes"><h2>Notes</h2>${model.notes.map(note => `<p>${esc(note)}</p>`).join("")}</section>` : "";
  const orientation = Math.max(0, ...model.sections.map(item => item.columns.length)) > 6 ? "landscape" : "portrait";
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${esc(model.title)}</title><style>${BRANDED_DOCUMENT_BASE_CSS}@page{size:A4 ${orientation};margin:12mm}.report{width:100%}.company-report-header{padding-bottom:5mm;border-bottom:2px solid #0d6658}.report-title{margin:7mm 0 5mm}.report-title h1{font-size:22px;margin:0 0 2mm}.meta{display:flex;gap:8mm;flex-wrap:wrap;color:#6b7c81;font-size:10px}.metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:3mm;margin:5mm 0}.metrics article{border:1px solid #d9e1e2;border-radius:2mm;padding:4mm;break-inside:avoid}.metrics span,.metrics small{display:block;color:#6b7c81;font-size:9px}.metrics strong{display:block;margin:1.5mm 0;font-size:15px}.report-section,.notes{margin-top:6mm}.report-section h2,.notes h2{font-size:13px;color:#12352d}table{width:100%;border-collapse:collapse;font-size:9px}th{background:#12352d;color:#fff;text-align:left}th,td{padding:2.5mm;border:1px solid #d9e1e2;vertical-align:top}.notes p{font-size:9px;color:#6b7c81}@media print{.report-section{break-before:auto}}</style></head><body><main class="report"><header class="company-report-header">${renderCompanyIdentity(company, model.country)}</header><div class="report-title"><h1>${esc(model.title)}</h1><div class="meta"><span>Period: ${esc(model.period)}</span><span>Generated: ${esc(generatedAt.toLocaleString("en-GB"))}</span><span>Currency: ${esc(model.currency)}</span></div></div>${metrics}${sections}${notes}${renderInfoBridgeFooter({ company, country: model.country, label: model.title, generatedAt })}</main><script>(()=>{let closing=false;const closePrintWindow=()=>{if(closing)return;closing=true;setTimeout(()=>window.close(),0)};addEventListener("afterprint",closePrintWindow,{once:true});addEventListener("load",()=>setTimeout(()=>{addEventListener("focus",()=>setTimeout(closePrintWindow,250),{once:true});window.print()},150),{once:true})})();</script></body></html>`;
}
