import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{ACTIONS,MODULES,ROLE_TEMPLATES,bootstrap,defaultState}from"../src/administration/core.js";
const read=path=>readFileSync(new URL(path,import.meta.url),"utf8"),app=read("../src/administration/app.js"),sql=read("../supabase/company-member-permissions.sql"),api=read("../src/company/member-permissions.js"),client=read("../src/supabase/client.js"),adminSql=read("../supabase/company-admin-invitations.sql");

test("only Owner and Administrator remain protected local system roles",()=>{assert.deepEqual(ROLE_TEMPLATES,["Owner","Administrator"]);const source=defaultState(),company={id:"CO-1",active:true};Object.assign(source,{companies:[company],currentCompanyId:company.id,roles:[{id:"OLD",companyId:company.id,name:"Sales Manager"},{id:"COPY",companyId:company.id,name:"Owner Copy"}]});const state=bootstrap(source);assert.deepEqual(state.roles.map(x=>x.name).sort(),["Administrator","Owner"]);for(const role of state.roles)for(const module of MODULES)for(const action of ACTIONS)assert.equal(role.permissions[module][action],true)});
test("Roles page has protected roles and accepted members without create duplicate or preview actions",()=>{const view=app.slice(app.indexOf("function roles()"),app.indexOf("function moduleAccess()"));assert.match(view,/Protected System Roles/);assert.match(view,/Accepted Company Members/);assert.match(view,/Edit Permissions/);assert.match(view,/Remove Access/);assert.doesNotMatch(view,/Duplicate|Create custom role|Preview as Role/);assert.doesNotMatch(app,/data-duplicate-role/)});
test("accepted active memberships are the only normal members in the role directory",()=>{assert.match(sql,/m\.company_id=p_company_id and m\.status='active' and m\.system_role in \('company_admin','company_member'\)/);assert.match(sql,/invitation\.status='accepted'/);assert.doesNotMatch(sql,/invitation\.status='pending'/);assert.match(api,/company_role_directory/)});
test("permissions are stored per company and normal member",()=>{assert.match(sql,/permissions jsonb not null default/);assert.match(sql,/m\.id=p_member_id and m\.company_id=p_company_id and m\.system_role='company_member'/);assert.match(sql,/private\.can_manage_company_members\(p_company_id\)/);assert.match(app,/updateCompanyMemberPermissions\(globalThis\.InfoBridgeCompany\.companyId,member\.member_id,next\)/);assert.match(client,/access_permissions:data\.permissions/)});
test("Owner and Company Admin are view-only protected rows",()=>{assert.match(app,/\["owner","company_admin"\]\.includes\(member\.system_role\)/);assert.match(app,/readonly\|\|fixed/);assert.match(sql,/m\.system_role='company_member'/);assert.doesNotMatch(sql,/set status='inactive'.*system_role='company_admin'/s)});
test("normal access removal is revocation only and never touches HR or ownership",()=>{assert.match(sql,/set status='inactive'/);assert.doesNotMatch(sql,/delete from public\.company_members/);assert.doesNotMatch(sql,/workspace_records|employees|hr-payroll|owner_id\s*=/);assert.match(app,/HR employee records will not be changed/)});
test("existing Owner to Company Admin invitation remains separate",()=>{assert.match(adminSql,/create_company_admin_invitation/);assert.match(adminSql,/accept_company_admin_invitation/);assert.doesNotMatch(sql,/create_company_admin_invitation|accept_company_admin_invitation/)});
