import test from"node:test";import assert from"node:assert/strict";import{administrationBranchFormModel,branchTaxTypes,normalizeAdministrationBranchInput,orderedCompanyBranches,reconcileCompanyHeadOffice,saveConfiguredBranch}from"../src/administration/branch-form.js";import{defaultState}from"../src/administration/core.js";
const uae={id:"CO-AE",tradeName:"shayay hospitality",legalName:"shayay hospitality",country:"AE",state:"Dubai",city:"Dubai",businessAddress:"Dubai address",taxSystem:"VAT",trn:"100000000000003",email:"owner@example.com",mobile:"0500000000"};
const india={id:"CO-IN",tradeName:"India Co",country:"IN",state:"Tamil Nadu",city:"Chennai",taxSystem:"GST",gstin:"33AAAAA0000A1Z5"};
function state(companies=[uae]){return{...defaultState(),currentCompanyId:companies[0].id,companies,branches:[]}}
test("missing UAE Head Office is initialized once from the current company",()=>{const s=state();reconcileCompanyHeadOffice(s,uae);reconcileCompanyHeadOffice(s,uae);assert.equal(s.branches.length,1);const h=s.branches[0];assert.deepEqual([h.companyId,h.name,h.code,h.country,h.region,h.taxType,h.trn,h.address,h.isDefault],[uae.id,"Head Office","HO","AE","Dubai","VAT","100000000000003","Dubai address",true])});
test("legacy placeholder Head Office is reconciled rather than duplicated",()=>{const s=state();s.branches.push({id:"LEGACY-HO",companyId:uae.id,name:"Head Office",code:"HO",country:"India",state:"Tamil Nadu",placeholder:true,isDefault:true});reconcileCompanyHeadOffice(s,uae);assert.equal(s.branches.length,1);assert.deepEqual([s.branches[0].id,s.branches[0].country,s.branches[0].region,s.branches[0].placeholder],["LEGACY-HO","AE","Dubai",false])});
test("UAE branches add, edit, refresh and retain separate records",()=>{let s=state();reconcileCompanyHeadOffice(s,uae);let result=saveConfiguredBranch(s,{name:"Abu Dhabi Branch",code:"AUH",country:"AE",region:"Abu Dhabi",taxType:"VAT",taxNumber:"100000000000003",address:"AUH",city:"Abu Dhabi",postalCode:"00000"},uae);s=result.state;const id=result.record.id;assert.equal(s.branches.length,2);result=saveConfiguredBranch(s,{...result.record,name:"Abu Dhabi Office",region:"Abu Dhabi",taxType:"VAT",taxNumber:"100000000000003",city:"Abu Dhabi"},uae);s=JSON.parse(JSON.stringify(result.state));assert.equal(s.branches.length,2);assert.equal(s.branches.find(x=>x.id===id).name,"Abu Dhabi Office");assert.equal(s.branches.find(x=>x.code==="HO").name,"Head Office")});
test("India and No Tax branches use the same normalized contract",()=>{const gst=normalizeAdministrationBranchInput({name:"Chennai",code:"MAA",country:"IN",region:"Tamil Nadu",taxType:"GST",taxNumber:"33AAAAA0000A1Z5",city:"Chennai",postalCode:"600001"},india),none=normalizeAdministrationBranchInput({name:"Dubai",code:"DXB",country:"AE",region:"Dubai",taxType:"No Tax",city:"Dubai"},uae);assert.deepEqual([gst.state,gst.gstin,gst.pinCode],["Tamil Nadu","33AAAAA0000A1Z5","600001"]);assert.deepEqual([none.taxNumber,none.gstin,none.trn],["","",""])});
test("legacy India and UAE branches load through common fields",()=>{const i=administrationBranchFormModel({country:"India",state:"Kerala",gstin:"32AAAAA0000A1Z5",pinCode:"682001"},india),a=administrationBranchFormModel({country:"UAE",emirate:"Sharjah",trn:"100000000000003"},uae);assert.deepEqual([i.region,i.taxType,i.taxNumber,i.postalCode],["Kerala","GST","32AAAAA0000A1Z5","682001"]);assert.deepEqual([a.region,a.taxType,a.taxNumber],["Sharjah","VAT","100000000000003"])});
test("branches are company-isolated, Head Office first, and only one default",()=>{let s=state([uae,india]);reconcileCompanyHeadOffice(s,uae);s=saveConfiguredBranch(s,{name:"Dubai Branch",code:"DXB",country:"AE",region:"Dubai",taxType:"No Tax",city:"Dubai",isDefault:true},uae).state;s.currentCompanyId=india.id;reconcileCompanyHeadOffice(s,india);assert.deepEqual(orderedCompanyBranches(s.branches,uae.id).map(x=>x.code),["HO","DXB"]);assert.deepEqual(orderedCompanyBranches(s.branches,india.id).map(x=>x.code),["HO"]);assert.equal(s.branches.filter(x=>x.companyId===uae.id&&x.isDefault).length,1);assert.throws(()=>saveConfiguredBranch(s,{...s.branches.find(x=>x.companyId===uae.id),name:"Wrong edit"},india),/another company/)});
test("country controls region and tax options without mixed jurisdictions",()=>{const mixed=administrationBranchFormModel({id:"BR-X",country:"India",region:"Abu Dhabi",taxType:"VAT"},uae),indiaModel=administrationBranchFormModel({country:"IN",region:"Tamil Nadu",taxType:"GST"},uae),uaeModel=administrationBranchFormModel({country:"AE",region:"Dubai",taxType:"VAT"},india);assert.equal(mixed.region,"");assert.equal(mixed.taxType,"No Tax");assert.deepEqual(branchTaxTypes("IN"),["GST","No Tax"]);assert.deepEqual(branchTaxTypes("AE"),["VAT","No Tax"]);assert.ok(indiaModel.regions.includes("Tamil Nadu")&&!indiaModel.regions.includes("Abu Dhabi"));assert.ok(uaeModel.regions.includes("Abu Dhabi")&&!uaeModel.regions.includes("Tamil Nadu"))});
test("invalid country region and tax combinations are rejected before save",()=>{assert.throws(()=>normalizeAdministrationBranchInput({country:"IN",region:"Abu Dhabi",taxType:"GST",taxNumber:"33AAAAA0000A1Z5"},india),/valid Region/);assert.throws(()=>normalizeAdministrationBranchInput({country:"IN",region:"Tamil Nadu",taxType:"VAT",taxNumber:"100000000000003"},india),/not a valid Tax Type/);assert.throws(()=>normalizeAdministrationBranchInput({country:"AE",region:"Dubai",taxType:"GST",taxNumber:"33AAAAA0000A1Z5"},uae),/not a valid Tax Type/)});
test("mixed legacy default Head Office is repaired once from its company",()=>{const s=state();s.branches.push({id:"MIXED-HO",companyId:uae.id,name:"Head Office",code:"HO",country:"IN",region:"Abu Dhabi",state:"Abu Dhabi",taxType:"VAT",address:"chennai",isDefault:true});reconcileCompanyHeadOffice(s,uae);const head=s.branches[0];assert.deepEqual([head.country,head.region,head.taxType,head.address],["AE","Dubai","VAT","Dubai address"]);head.region="Sharjah";head.state="Sharjah";head.address="User office";reconcileCompanyHeadOffice(s,uae);assert.deepEqual([head.region,head.address],["Sharjah","User office"])});
