import test from"node:test";import assert from"node:assert/strict";import{ACTIONS,MODULES,bootstrap,can,defaultState,getCurrentFinancialYear,isDateInOpenPeriod,nextNumber,saveBranch,saveCompany,saveDepartment,saveFinancialYear,saveMaster,saveRole,saveSequence,switchCompany,taxMode}from"../src/administration/core.js";import{companyBackup,simpleChecksum,validateBackup}from"../src/administration/repository.js";
test("bootstrap is idempotent and creates one default company and branch",()=>{const a=bootstrap(defaultState()),b=bootstrap(a);assert.equal(b.companies.length,1);assert.equal(b.branches.length,1);assert.equal(b.companies[0].id,a.companies[0].id)});
test("companies isolate branches and switch without copying records",()=>{let s=bootstrap(defaultState()),r=saveCompany(s,{legalName:"Second Pvt Ltd",tradeName:"Second",businessType:"Private Limited",gstStatus:"Unregistered",country:"India",state:"Kerala",city:"Kochi",currency:"INR",timezone:"Asia/Kolkata"});s=switchCompany(r.state,r.record.id);assert.equal(s.currentCompanyId,r.record.id);assert.equal(s.branches.filter(x=>x.companyId===r.record.id).length,1);assert.equal(s.branches.filter(x=>x.companyId!==r.record.id).length,1)});
test("branch and department codes are unique per company",()=>{let s=bootstrap(defaultState());s=saveBranch(s,{name:"South",code:"S",country:"India",state:"Tamil Nadu",city:"Chennai"}).state;assert.throws(()=>saveBranch(s,{name:"Other",code:"s",country:"India",state:"Tamil Nadu",city:"Chennai"}),/unique/);s=saveDepartment(s,{name:"Sales",code:"SAL"}).state;assert.throws(()=>saveDepartment(s,{name:"Sales 2",code:"sal"}),/exists/)});
test("financial years reject overlap and enforce open periods",()=>{let s=bootstrap(defaultState());assert.ok(getCurrentFinancialYear(s));assert.throws(()=>saveFinancialYear(s,{label:"Overlap",startDate:s.financialYears[0].startDate,endDate:s.financialYears[0].endDate,status:"Upcoming"}),/overlap/);assert.equal(isDateInOpenPeriod(s,s.financialYears[0].startDate),true);s.financialYears[0].lockDate=s.financialYears[0].startDate;assert.equal(isDateInOpenPeriod(s,s.financialYears[0].startDate),false)});
test("document numbering remains unique and sequential",()=>{let s=bootstrap(defaultState()),r=saveSequence(s,{documentType:"GST Invoice",prefix:"INV/{FY}/",suffix:"",startingNumber:1,padding:4,resetFrequency:"Financial Year"});let a=nextNumber(r.state,r.record.id),b=nextNumber(a.state,r.record.id);assert.match(a.number,/INV\/\d{4}-\d{2}\/0001/);assert.notEqual(a.number,b.number);assert.equal(b.state.documentSequences[0].usedNumbers.length,2)});
test("permission service supports restricted preview without changing owner",()=>{let s=bootstrap(defaultState()),p=Object.fromEntries(MODULES.map(m=>[m,Object.fromEntries(ACTIONS.map(a=>[a,m==="Sales & CRM"&&a==="View"]))])),r=saveRole(s,{name:"Sales View",permissions:p});s=r.state;assert.equal(can(s,"Sales & CRM","View",r.record.id),true);assert.equal(can(s,"Banking","View",r.record.id),false);assert.equal(can(s,"Administration","Manage Permissions"),true)});
test("tax mode never enables IGST with CGST and SGST",()=>{assert.deepEqual(taxMode("27","27"),{cgst:true,sgst:true,igst:false});assert.deepEqual(taxMode("27","29"),{cgst:false,sgst:false,igst:true})});
test("shared masters reject duplicates and backups validate checksums",()=>{let s=bootstrap(defaultState());s=saveMaster(s,{type:"Units",name:"Piece",code:"PCS"}).state;assert.throws(()=>saveMaster(s,{type:"Units",name:"piece"}),/Duplicate/);const b=companyBackup(s,s.currentCompanyId,{sales:{invoices:[]}});assert.equal(validateBackup(b).companyName,s.companies[0].legalName);b.companyName="Tampered";assert.throws(()=>validateBackup(b),/checksum/)});
