import test from"node:test";import assert from"node:assert/strict";import{initialState,saveAccount,recordTransaction,accountBalance,createTransfer,previewImport,confirmImport,startReconciliation,completeReconciliation,reopenReconciliation,closeCash,saveCheque,changeChequeStatus,saveRule,previewRule}from"../src/banking/core.js";
function account(s,name,type,balance=0){return saveAccount(s,{name,type,currency:"INR",openingBalance:balance,openingBalanceDate:"2026-04-01"})}function seeded(){let s=initialState(),a=account(s,"Operating","Current Bank Account",1000);s=a.state;let c=account(s,"Cash","Cash Account",500);return{state:c.state,bank:a.record,cash:c.record}}
test("accounts and money movement retain traceable balances",()=>{let{state,bank}=seeded();state=recordTransaction(state,{accountId:bank.id,date:"2026-08-01",direction:"In",amount:250,category:"Customer Payment",description:"Invoice receipt"}).state;assert.equal(accountBalance(state,bank.id),1250);assert.equal(state.integration.finance.length,1)});
test("transfers create a linked pair and charge without changing combined principal",()=>{let{state,bank,cash}=seeded();const before=accountBalance(state,bank.id)+accountBalance(state,cash.id);const r=createTransfer(state,{fromAccountId:bank.id,toAccountId:cash.id,date:"2026-08-02",amount:200,charges:10});assert.equal(r.record.transactionIds.length,3);assert.equal(accountBalance(r.state,bank.id)+accountBalance(r.state,cash.id),before-10)});
test("statement preview rejects bad rows and skips duplicates",()=>{let{state,bank}=seeded(),args={accountId:bank.id,rows:[{Date:"01/08/2026",Narration:"Receipt",Credit:"100"},{Date:"bad",Narration:"Broken",Credit:"50"}],mapping:{date:"Date",description:"Narration",credit:"Credit"},dateFormat:"DD/MM/YYYY",fileName:"bank.csv"};let p=previewImport(state,args);assert.equal(p[0].status,"Valid");assert.equal(p[1].status,"Rejected");state=confirmImport(state,p,{...args,profileName:"Bank CSV"}).state;p=previewImport(state,args);assert.equal(p[0].status,"Duplicate");assert.equal(state.mappingProfiles.length,1)});
test("reconciliation completes and can be reopened with reasons",()=>{let{state,bank}=seeded();let r=startReconciliation(state,{accountId:bank.id,startDate:"2026-08-01",endDate:"2026-08-31",reconciliationDate:"2026-08-31",openingStatementBalance:1000,closingStatementBalance:1000});state=completeReconciliation(r.state,r.record.id);assert.equal(state.reconciliations[0].status,"Completed");state=reopenReconciliation(state,r.record.id,"Statement amended");assert.equal(state.reconciliations[0].status,"Reopened")});
test("cash closing records controlled variance and cheque clearance creates activity",()=>{let{state,cash}=seeded();state=closeCash(state,{accountId:cash.id,date:"2026-08-01",physicalCash:510,closedBy:"Owner",reason:"Cash count correction"}).state;assert.equal(state.cashClosings[0].difference,10);let c=saveCheque(state,{chequeNumber:"123",accountId:cash.id,direction:"In",amount:100,date:"2026-08-01"});state=changeChequeStatus(c.state,c.record.id,"Deposited/Presented");state=changeChequeStatus(state,c.record.id,"Cleared");assert.ok(state.cheques[0].transactionId)});
test("bank rules preview only matching real transactions",()=>{let{state,bank}=seeded();state=recordTransaction(state,{accountId:bank.id,date:"2026-08-01",direction:"Out",amount:25,category:"Business Expense",description:"MONTHLY BANK FEE",negativeConfirmed:true}).state;let r=saveRule(state,{name:"Fees",field:"description",operator:"contains",value:"bank fee",actionType:"category",actionValue:"Bank Charge",priority:10});assert.equal(previewRule(r.state,r.record.id).length,1)});
test("local calendar dates do not shift through UTC",()=>{const local={getFullYear:()=>2026,getMonth:()=>7,getDate:()=>30,toISOString:()=>"2026-08-29T20:00:00.000Z"};assert.equal(localDate(local),"2026-08-30")});
test("dashboard and reconciliation use the authoritative ledger exactly once",()=>{let{state,bank}=seeded();state=recordTransaction(state,{accountId:bank.id,date:"2026-08-30",direction:"In",amount:500,category:"Customer Payment",description:"Receipt"}).state;state=recordTransaction(state,{accountId:bank.id,date:"2026-08-30",direction:"Out",amount:200,category:"Business Expense",description:"Payment"}).state;const metrics=dashboardMetrics(state,{getFullYear:()=>2026,getMonth:()=>7,getDate:()=>30});assert.equal(metrics.bankBalance,1300);assert.equal(metrics.inToday,500);assert.equal(metrics.outToday,200);const reconciliation=startReconciliation(state,{accountId:bank.id,startDate:"2026-08-01",endDate:"2026-08-30",reconciliationDate:"2026-08-30",openingStatementBalance:1000,closingStatementBalance:1300}).record;assert.equal(reconciliation.bookOpening,1000);assert.equal(reconciliation.periodMovement,300);assert.equal(reconciliation.bookClosing,1300);assert.equal(reconciliation.difference,0)});
test("Sales payment sync is idempotent, traceable, and reverses once",()=>{let{state,bank}=seeded();const payment={id:"RCPT/2026-27/0001",invoiceId:"INV/2026-27/0001",customerId:"CUS-1",date:"2026-08-30",amount:7875,mode:"Bank Transfer",reference:"ABC-ADV-001"},context={invoice:{id:payment.invoiceId},customer:{name:"ABC Real Estate LLC"},accountId:bank.id};let result=syncSalesPayment(state,payment,context);state=result.state;assert.equal(accountBalance(state,bank.id),8875);assert.equal(state.transactions.filter(x=>x.sourceId===payment.id).length,1);result=syncSalesPayment(state,payment,context);assert.equal(result.duplicate,true);assert.equal(result.state.transactions.filter(x=>x.sourceId===payment.id).length,1);const reversed=reverseSalesPayment(result.state,payment.id,"Payment reversed");assert.equal(accountBalance(reversed.state,bank.id),1000);assert.equal(reverseSalesPayment(reversed.state,payment.id,"Again").duplicate,true)});
test("invalid financial dates and repeated reversals are rejected",()=>{let{state,bank}=seeded();assert.throws(()=>recordTransaction(state,{accountId:bank.id,date:"2026-02-31",direction:"In",amount:1,category:"Other Income",description:"Bad date"}),/valid transaction date/);state=recordTransaction(state,{accountId:bank.id,date:"2026-08-30",direction:"In",amount:1,category:"Other Income",description:"Valid"}).state;const id=state.transactions[0].id;state=reverseTransaction(state,id,"Correction");assert.throws(()=>reverseTransaction(state,id,"Again"),/already reversed/)});
import{dashboardMetrics,localDate,reverseTransaction}from"../src/banking/core.js";
import{reverseSalesPayment,syncSalesPayment}from"../src/banking/sales-sync.js";
import{readFileSync}from"node:fs";
import{updateReconciliation}from"../src/banking/core.js";
test("reconciliation actions use in-app modals and expose Resume only after reopening",()=>{const source=readFileSync(new URL("../src/banking/app.js",import.meta.url),"utf8"),flow=source.slice(source.indexOf('document.addEventListener("click",event=>{const completeButton'));assert.match(source,/title:"Adjustment Reason"/);assert.match(source,/title:"Reopen Reconciliation"/);assert.match(source,/Reason for reopening is required\./);assert.match(source,/data-reconciliation-edit/);assert.match(source,/>Resume<\/button>/);assert.match(source,/label:"Complete Reconciliation"/);assert.match(flow,/difference===0/);assert.doesNotMatch(flow,/prompt\(|alert\(|confirm\(/)});
test("completed reconciliation can reopen, resume without ledger mutation, and complete again",()=>{let{state,bank}=seeded();state=recordTransaction(state,{accountId:bank.id,date:"2026-08-30",direction:"In",amount:500,category:"Customer Payment",description:"Receipt"}).state;state=recordTransaction(state,{accountId:bank.id,date:"2026-08-30",direction:"Out",amount:200,category:"Business Expense",description:"Payment"}).state;const balanceBefore=accountBalance(state,bank.id),transactionsBefore=structuredClone(state.transactions);let result=startReconciliation(state,{accountId:bank.id,startDate:"2026-08-01",endDate:"2026-08-30",reconciliationDate:"2026-08-30",openingStatementBalance:1000,closingStatementBalance:1300});state=completeReconciliation(result.state,result.record.id);state=reopenReconciliation(state,result.record.id,"Test reopen");let reconciliation=state.reconciliations.find(x=>x.id===result.record.id);assert.equal(reconciliation.status,"Reopened");assert.equal(reconciliation.reopenReason,"Test reopen");result=updateReconciliation(state,reconciliation.id,{accountId:bank.id,startDate:"2026-08-01",endDate:"2026-08-30",reconciliationDate:"2026-08-30",openingStatementBalance:1000,closingStatementBalance:1300});state=result.state;reconciliation=result.record;assert.equal(reconciliation.bookClosing,1300);assert.equal(reconciliation.difference,0);assert.equal(state.reconciliations.filter(x=>x.id===reconciliation.id).length,1);state=completeReconciliation(state,reconciliation.id);reconciliation=state.reconciliations.find(x=>x.id===reconciliation.id);assert.equal(reconciliation.status,"Completed");assert.deepEqual(reconciliation.history.map(x=>x.action),["Created","Completed","Reopened","Edited after reopen","Completed"]);assert.equal(accountBalance(state,bank.id),balanceBefore);assert.deepEqual(state.transactions.map(({reconciliationStatus,...x})=>x),transactionsBefore.map(({reconciliationStatus,...x})=>x))});
