import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
import{RESET_MODULES,masterKeyFormState}from"../src/security/client.js";

const sql=readFileSync(new URL("../supabase/company-security.sql",import.meta.url),"utf8"),client=readFileSync(new URL("../src/security/client.js",import.meta.url),"utf8"),securityUi=readFileSync(new URL("../src/scripts/company-security.js",import.meta.url),"utf8"),hr=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8"),reset=readFileSync(new URL("../src/hr-payroll/employee-reset.js",import.meta.url),"utf8"),profile=readFileSync(new URL("../src/supabase/client.js",import.meta.url),"utf8"),page=readFileSync(new URL("../src/pages/marketing/company.js",import.meta.url),"utf8");

test("Master and department keys are salted hashes in a non-exposed schema",()=>{assert.match(sql,/create schema if not exists private/);assert.match(sql,/master_key_hash text not null/);assert.match(sql,/reset_key_hash text not null/);assert.match(sql,/extensions\.crypt\(p_new_key,extensions\.gen_salt\('bf',12\)\)/);assert.match(sql,/revoke all on all tables in schema private from public, anon, authenticated/);assert.doesNotMatch(profile,/masterKey|resetKey|master_key_hash|reset_key_hash/)});
test("owner authority is derived from companies owner_id and auth uid",()=>{assert.match(sql,/owner_id=auth\.uid\(\)/);assert.match(sql,/if not private\.is_company_owner\(p_company_id\).*Not authorized/s);assert.match(sql,/security definer/g);assert.match(securityUi,/profile\.ownerId!==user\.id/)});
test("Master Key setup change and verification stay in trusted RPCs",()=>{for(const name of["configure_company_master_key","verify_company_master_key","change_company_master_key"])assert.match(sql,new RegExp(`function public\\.${name}`));assert.match(sql,/master_key_hash=extensions\.crypt\(coalesce\(p_key,''\),s\.master_key_hash\)/);assert.match(sql,/Master Key verification failed/);assert.doesNotMatch(client,/crypto|localStorage|sessionStorage/)});
test("department keys require Master Key and remain module scoped",()=>{assert.deepEqual(RESET_MODULES.map(module=>module.id),["hr_payroll","sales_crm","purchases","inventory","finance","banking","projects"]);assert.match(sql,/if not private\.check_master_key\(p_company_id,p_master_key\)/);assert.match(sql,/primary key \(company_id, module_id\)/);assert.match(sql,/p_module_id<>'hr_payroll'.*not implemented/s)});
test("HR reset uses server authorization and an exact destructive whitelist",()=>{assert.match(hr,/executeHrReset\(companyId,values\.resetKey,values\.confirmation\)/);assert.match(hr,/field\("resetKey","HR Reset Key","password"/);assert.match(reset,/const authorization = await authorizeReset\(\)/);assert.doesNotMatch(reset,/resetEmployeeData\(cloudStore\)/);for(const collection of["employees","attendance","leaveTransactions","payrollRuns","payslips"])assert.match(sql,new RegExp(`'${collection}'`));assert.match(sql,/module='hr-payroll'/)});
test("HR key cannot authorize another module or company-wide actions",()=>{assert.match(sql,/p_module_id<>'hr_payroll'/);assert.doesNotMatch(sql,/function public\.(reset_entire_company|delete_company)/);assert.match(page,/Reset Entire Company — Unavailable/);assert.doesNotMatch(page,/Delete Company — Unavailable/,"Delete Company is intentionally enabled -- it is gated by the owner's Master Key, not by any department reset key");assert.match(page,/data-delete-company-open/)});
test("wrong-key throttling locks verification after five failures",()=>{assert.match(sql,/failed_attempts\+1>=5/);assert.match(sql,/interval '15 minutes'/);assert.match(sql,/Security verification temporarily locked/)});
test("security audit stores only non-secret action metadata",()=>{assert.match(sql,/company_security_audit/);for(const action of["master_key_configured","master_key_changed","department_reset_key_configured","department_reset_key_revoked","department_reset_executed"])assert.match(sql,new RegExp(action));assert.doesNotMatch(sql,/insert into private\.company_security_audit[^;]*(master_key|reset_key)/s)});
test("security foundation is country independent and existing companies need no security row",()=>{assert.doesNotMatch(sql,/\bIN\b|\bAE\b|GST|VAT/);assert.match(sql,/create table if not exists private\.company_security/);assert.doesNotMatch(sql,/insert into private\.company_security\s*select/)});
test("trusted status selects initial setup and removes the nonexistent current key from submission",()=>{const view=masterKeyFormState({masterConfigured:false});assert.equal(view.title,"Set Up Company Master Key");assert.equal(view.confirmationLabel,"Confirm Master Key");assert.equal(view.actionLabel,"Set Up Master Key");assert.equal(view.configured,false);assert.match(securityUi,/currentKeyInput\.required=view\.configured/);assert.match(securityUi,/currentKeyInput\.disabled=!view\.configured/);assert.match(securityUi,/currentKeyField\.remove\(\)/);assert.match(securityUi,/companySecurityStatus\(company\.companyId\)/);assert.doesNotMatch(securityUi,/localStorage\.setItem|sessionStorage\.setItem/)});
test("refresh after setup selects change state and requires the current key",()=>{const view=masterKeyFormState({masterConfigured:true});assert.equal(view.title,"Change Company Master Key");assert.equal(view.confirmationLabel,"Confirm New Master Key");assert.equal(view.actionLabel,"Change Master Key");assert.equal(view.configured,true);assert.match(securityUi,/await configureMasterKey\(company\.companyId,values\.newKey\)/);assert.match(securityUi,/await refresh\(\)/);assert.match(securityUi,/await changeMasterKey\(company\.companyId,values\.currentKey,values\.newKey\)/)});
test("Master Key onboarding remains identical for India and UAE companies",()=>{for(const country of["IN","AE"])assert.deepEqual(masterKeyFormState({masterConfigured:false,country}),masterKeyFormState({masterConfigured:false}))});
test("all bcrypt calls resolve pgcrypto through the Supabase extensions schema",()=>{assert.match(sql,/create extension if not exists pgcrypto with schema extensions/);assert.doesNotMatch(sql,/(?<!extensions\.)\b(?:crypt|gen_salt)\(/);assert.equal((sql.match(/extensions\.gen_salt\('bf',12\)/g)||[]).length,3);assert.equal((sql.match(/extensions\.crypt\(/g)||[]).length,5)});
test("first-time Master Key configuration enters the workspace, but changing an existing key stays on the page",()=>{assert.match(securityUi,/if\(wasConfigured\)\{await changeMasterKey\(company\.companyId,values\.currentKey,values\.newKey\);masterForm\.reset\(\);message\("Master Key changed\. Department Reset Keys remain valid\."\);await refresh\(\)\}else\{await configureMasterKey\(company\.companyId,values\.newKey\);location\.replace\(destinationAfterAuth\(sessionStorage\)\)\}/);assert.match(securityUi,/import\{destinationAfterAuth\}from"\/auth\/core\.js"/)});
