import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
const read=path=>readFileSync(new URL(path,import.meta.url),"utf8"),sql=read("../supabase/company-member-invitations.sql"),api=read("../src/company/member-invitations.js"),app=read("../src/administration/app.js"),page=read("../src/pages/marketing/company.js"),accept=read("../src/scripts/company-member-invite.js"),auth=read("../src/scripts/auth-ui.js"),adminSql=read("../supabase/company-admin-invitations.sql"),adminApi=read("../src/company/admin-invitations.js");

test("active Company Admin or owner can manage only their server-verified company",()=>{assert.match(sql,/private\.is_company_admin\(p_company_id\)/);assert.match(sql,/m\.company_id=p_company_id.*m\.user_id=auth\.uid\(\).*m\.system_role='company_admin'.*m\.status='active'/s);assert.match(sql,/if not private\.can_manage_company_members\(p_company_id\).*Not authorized/s);assert.match(sql,/i\.id=p_invitation_id and i\.company_id=p_company_id/)});
test("normal invitation data is secure normalized expiring and company scoped",()=>{assert.match(sql,/create table if not exists private\.company_member_invitations/);assert.match(sql,/v_email text:=lower\(trim/);assert.match(sql,/extensions\.gen_random_bytes\(32\)/);assert.match(sql,/extensions\.digest\(v_token,'sha256'\)/);assert.match(sql,/status in \('pending','accepted','cancelled','expired'\)/);assert.doesNotMatch(sql,/(?:^|\n)\s*token text not null/)});
test("directory reload returns the authoritative invitation lifecycle",()=>{assert.match(sql,/public\.company_member_directory/);assert.match(sql,/from private\.company_member_invitations i where i\.company_id=p_company_id/);assert.match(sql,/i\.status/);assert.match(api,/company_member_directory/);assert.match(app,/refreshMembers/)});
test("resend rotates one pending invitation and cancel invalidates it",()=>{assert.match(sql,/resend_company_member_invitation/);assert.match(sql,/set token_hash=extensions\.digest\(v_token,'sha256'\)/);assert.match(sql,/cancel_company_member_invitation/);assert.match(sql,/set status='cancelled'/);assert.match(app,/data-resend-member/);assert.match(app,/data-cancel-member/)});
test("acceptance rejects invalid state expiry and wrong authenticated email",()=>{assert.match(sql,/if v\.status<>'pending'/);assert.match(sql,/if v\.expires_at<=now\(\)/);assert.match(sql,/if v\.invited_email<>v_email/);assert.match(sql,/Invitation is invalid/)});
test("acceptance creates exactly one normal membership and never admin access",()=>{assert.match(adminSql,/unique\(company_id,user_id\)/);assert.match(sql,/values\(v\.company_id,auth\.uid\(\),v\.invited_email,v\.invited_name,v\.position,'company_member','active'/);assert.match(sql,/if exists\(select 1 from public\.company_members m where m\.company_id=v\.company_id and m\.user_id=auth\.uid\(\)\)/);assert.doesNotMatch(sql,/values\(v\.company_id,auth\.uid\(\).*'company_admin'/s)});
test("Users and Members is one page with a permanent form and no account card or invite modal",()=>{const memberView=app.slice(app.indexOf("function members()"),app.indexOf("function roles()"));assert.match(memberView,/Manage company users and invitations\./);assert.match(memberView,/data-member-invite-form/);assert.match(memberView,/Invited Members/);assert.doesNotMatch(memberView,/Current account/);assert.doesNotMatch(memberView,/data-invite-member/);assert.doesNotMatch(memberView,/memberInviteForm/);assert.doesNotMatch(memberView,/Future company members/)});
test("invitation persists first last email position and department",()=>{for(const field of ["first_name","last_name","invited_email","position","department_id","department_name"])assert.match(sql,new RegExp(`\\b${field}\\b`));assert.match(api,/p_first_name:firstName/);assert.match(api,/p_last_name:lastName/);assert.match(api,/p_department_id:departmentId/);assert.match(app,/field\("firstName"/);assert.match(app,/field\("lastName"/);assert.match(app,/name="departmentId"/)});
test("department choices reuse active current-company Administration records and backend validation",()=>{assert.match(app,/rows\(state\.departments\)\.filter\(\(?x\)?=>x\.active&&!x\.retiredSystemDefault\)/);assert.match(app,/departments\.map/);assert.match(sql,/jsonb_array_elements\(coalesce\(wr\.data->'departments'/);assert.match(sql,/wr\.company_id=p_company_id/);assert.match(sql,/d->>'companyId'=p_company_id::text/);assert.match(sql,/d->>'id'=p_department_id/)});
test("database status drives pending accepted cancelled and expired display after refresh",()=>{assert.match(sql,/status in \('pending','accepted','cancelled','expired'\)/);assert.match(sql,/set status='accepted'/);assert.match(sql,/set status='cancelled'/);assert.match(sql,/set status='expired'/);assert.match(app,/x\.status/);assert.match(app,/refreshMembers/)});
test("missing RPC schema cache errors are replaced with a safe setup message",()=>{assert.match(app,/company_member_directory\|schema cache/);assert.match(app,/Database setup is required/);assert.doesNotMatch(app,/Could not find the function/)});
test("member acceptance supports matching-email login and signup",()=>{assert.match(page,/companyMemberInvitePage/);assert.match(accept,/acceptCompanyMemberInvitation\(token\)/);assert.match(accept,/memberInvite=/);assert.match(auth,/memberInvitationToken/);assert.match(auth,/company-member-invite\.html\?token/)});
test("email delivery is optional after authoritative RPC creation and localhost link is guarded",()=>{assert.match(api,/create_company_member_invitation/);assert.match(api,/optionalDelivery/);assert.match(api,/deliveryError/);assert.match(app,/\["localhost","127\.0\.0\.1","\[::1\]"\]/);assert.match(app,/Local test acceptance URL/)});
test("existing Company Admin invitation implementation remains present and separate",()=>{assert.match(adminSql,/create_company_admin_invitation/);assert.match(adminSql,/accept_company_admin_invitation/);assert.match(adminApi,/inviteFirstCompanyAdmin/);assert.doesNotMatch(sql,/create_company_admin_invitation/);assert.doesNotMatch(api,/inviteFirstCompanyAdmin/)});
