import test from"node:test";
import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
const read=path=>readFileSync(new URL(path,import.meta.url),"utf8"),sql=read("../supabase/company-admin-invitations.sql"),api=read("../src/company/admin-invitations.js"),profile=read("../src/scripts/company-profile.js"),page=read("../src/pages/marketing/company.js"),accept=read("../src/scripts/company-admin-invite.js"),client=read("../src/supabase/client.js"),context=read("../src/company/context.js"),workspace=read("../src/supabase/workspace.js"),auth=read("../src/scripts/auth-ui.js");

test("membership model keeps owner and extensible member identity separate",()=>{assert.match(sql,/create table if not exists public\.company_members/);assert.match(sql,/company_id uuid not null references public\.companies/);assert.match(sql,/user_id uuid not null references auth\.users/);assert.match(sql,/system_role text not null/);assert.match(sql,/unique\(company_id,user_id\)/);assert.doesNotMatch(sql,/update public\.companies set owner_id/)});
test("initial invitation creation is server-side owner only and duplicate safe",()=>{assert.match(sql,/create_company_admin_invitation/);assert.match(sql,/if not private\.is_company_owner\(p_company_id\).*Not authorized/s);assert.match(sql,/company_one_pending_bootstrap_admin_invitation/);assert.match(sql,/A Company Admin is already active/);assert.match(sql,/system_role text not null default 'company_admin'/)});
test("invitation token is random hashed expiring revocable and one-time",()=>{assert.match(sql,/gen_random_bytes\(32\)/);assert.match(sql,/extensions\.digest\(v_token,'sha256'\)/);assert.match(sql,/expires_at<=now\(\)/);assert.match(sql,/status='revoked'/);assert.match(sql,/status='accepted'/);assert.match(sql,/if v\.status<>'pending'/);assert.doesNotMatch(sql,/(?:^|\n)\s*token text not null/)});
test("acceptance enforces authenticated invited email and preserves company ownership",()=>{assert.match(sql,/auth\.jwt\(\)->>'email'/);assert.match(sql,/v\.invited_email<>v_email/);assert.match(sql,/insert into public\.company_members/);assert.match(sql,/'company_admin','active'/);assert.doesNotMatch(sql,/update public\.companies.*owner_id/s)});
test("Company Profile exposes only the owner bootstrap status and actions",()=>{assert.match(page,/Company Administration/);assert.match(page,/Invite Company Admin/);assert.match(page,/System Role: Company Admin/);assert.match(profile,/profile\?\.ownerId!==signedInUser\?\.id/);assert.match(profile,/companyAdminStatus/);assert.match(profile,/resendFirstCompanyAdminInvitation/);assert.match(profile,/revokeFirstCompanyAdminInvitation/)});
test("new and existing invited users share the matching-email acceptance route",()=>{assert.match(api,/signInWithOtp/);assert.match(api,/shouldCreateUser:true/);assert.match(api,/company-admin-invite\.html\?token/);assert.match(accept,/acceptCompanyAdminInvitation\(token\)/);assert.match(auth,/invitationDestination/);assert.match(auth,/emailRedirectTo.*invitationDestination/)});
test("current company and workspace access resolve active membership without weakening owner-only security",()=>{assert.match(client,/from\("company_members"\)/);assert.match(client,/\.eq\("status","active"\)/);assert.match(context,/\["company_admin","company_member"\]\.includes\(profile\.accessRole\)/);assert.match(workspace,/workspaceOwnerId\(company\)/);assert.match(sql,/private\.active_company_member\(company_id\)/);assert.match(read("../supabase/company-security.sql"),/private\.is_company_owner\(p_company_id\)/)});
test("company isolation is enforced in RLS and invitation membership scope",()=>{assert.match(sql,/company_id=v\.company_id/);assert.match(sql,/company_id=p_company_id/);assert.match(sql,/private\.active_company_member\(id\)/);assert.match(sql,/owner_id=\(select c\.owner_id from public\.companies c where c\.id=company_id\)/)});
test("RPC output names cannot collide with invitation table columns",()=>{assert.doesNotMatch(sql,/where company_id=p_company_id and status='pending' and expires_at/);assert.match(sql,/where i\.company_id=p_company_id and i\.status='pending' and i\.expires_at<=now\(\)/);assert.match(sql,/select i\.\* into v/);assert.match(sql,/where i\.token_hash=/)});
test("database invitation creation succeeds independently of optional email delivery",()=>{assert.match(api,/optionalDelivery/);assert.match(api,/deliveryError/);assert.match(api,/acceptanceUrl/);assert.match(profile,/localInvitationHost/);assert.match(page,/Local test acceptance URL/);assert.match(page,/data-local-invitation-url/)});
