import test from"node:test";
import assert from"node:assert/strict";
import{readFileSync}from"node:fs";
import{defaultState,saveDepartment}from"../src/administration/core.js";
import{absorbLegacyDepartments,departmentSelectOptions,ensureDefaultDepartments,orderedDepartments,sharedDepartmentName,sharedDepartments,stableDepartmentId}from"../src/administration/departments.js";
const company=id=>({id,name:id,active:true});
function memoryStorage(state,companyId=state.currentCompanyId){let value=JSON.stringify(state);return{companyId,getItem:key=>key==="infobridgeindia.administration.v2"?value:null,setItem:(key,next)=>{if(key==="infobridgeindia.administration.v2")value=next}}}

test("empty companies receive no module-generated departments or default module access",()=>{const state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A")],departments:[]};ensureDefaultDepartments(state);assert.deepEqual(state.departments,[]);assert.deepEqual(state.departmentDefaultAccess,[])});
test("migration retires old deterministic module departments without deleting historical IDs",()=>{const id=stableDepartmentId("CO-A","RPT"),state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A")],departments:[{id,companyId:"CO-A",name:"Reports & Analytics",code:"RPT",active:true,isSystem:true,systemDefault:true}]};ensureDefaultDepartments(state);assert.equal(state.departments.length,1);assert.equal(state.departments[0].active,false);assert.equal(state.departments[0].retiredSystemDefault,true);assert.deepEqual(orderedDepartments(state,"CO-A"),[]);assert.equal(orderedDepartments(state,"CO-A",{includeIds:[id]})[0].id,id)});
test("same-named company-created departments are never treated as application modules",()=>{const state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A")],departments:[{id:"MANUAL-SALES",companyId:"CO-A",name:"Sales & CRM",code:"SALES",active:true,isSystem:false,systemDefault:false}]};ensureDefaultDepartments(state);assert.equal(orderedDepartments(state,"CO-A")[0].id,"MANUAL-SALES");assert.equal(state.departments[0].active,true)});
test("department master is company scoped and active-only for new selections",()=>{const state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A"),company("CO-B")],departments:[{id:"A",companyId:"CO-A",name:"Housekeeping",code:"HK",active:true},{id:"OLD",companyId:"CO-A",name:"Old Team",code:"OLD",active:false},{id:"B",companyId:"CO-B",name:"Other Company",code:"OTHER",active:true}]},storage=memoryStorage(state,"CO-A");assert.deepEqual(sharedDepartments({storage}).map(x=>x.id),["A"]);assert.deepEqual(departmentSelectOptions("",{storage}).map(x=>x.id),["","A"]);assert.equal(sharedDepartments({storage,includeIds:["OLD"]}).find(x=>x.id==="OLD").name,"Old Team")});
test("Housekeeping create rename deactivate propagates by stable ID and preserves history",()=>{let state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A")],departments:[]};let saved=saveDepartment(state,{name:"Housekeeping",code:"HK",active:true});state=saved.state;const id=saved.record.id;let storage=memoryStorage(state);assert.equal(sharedDepartmentName(id,"",{storage}),"Housekeeping");saved=saveDepartment(state,{...saved.record,name:"Rooms Division"});state=saved.state;storage=memoryStorage(state);assert.equal(sharedDepartmentName(id,"",{storage}),"Rooms Division");saved=saveDepartment(state,{...saved.record,active:false});state=saved.state;storage=memoryStorage(state);assert.equal(sharedDepartments({storage}).some(x=>x.id===id),false);assert.equal(sharedDepartmentName(id,"",{storage}),"Rooms Division")});
test("legacy HR departments become real Administration departments, not module aliases",()=>{const state={...defaultState(),currentCompanyId:"CO-A",companies:[company("CO-A")],departments:[]},storage=memoryStorage(state);absorbLegacyDepartments([{id:"HR-OLD",name:"Human Resources",code:"HR",active:true}],storage);const rows=sharedDepartments({storage});assert.equal(rows.length,1);assert.deepEqual({id:rows[0].id,name:rows[0].name,isSystem:rows[0].isSystem},{id:"HR-OLD",name:"Human Resources",isSystem:false})});
test("HR and Internal Requests consume the shared Administration department helpers",()=>{const hr=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8"),requests=readFileSync(new URL("../src/approvals/app.js",import.meta.url),"utf8");assert.match(hr,/sharedDepartments\(\{includeIds:/);assert.match(requests,/departmentSelectOptions/);assert.match(requests,/sharedDepartmentName/)});
