import test from"node:test";import assert from"node:assert/strict";import{createDefaultChart,fromMinor,initialState,journalTotals,ledger,postJournal,reverseJournal,saveAccount,saveDraft,sourceKey,statements,toMinor,trialBalance}from"../src/finance/core.js";
const C="CO-1",B="BR-1";function chart(){return createDefaultChart(initialState(),C,B)}function id(s,n){return s.accounts.find(x=>x.name===n).id}
test("money uses integer paise and rejects excess precision",()=>{assert.equal(toMinor("123.45"),12345);assert.equal(fromMinor(12345),123.45);assert.throws(()=>toMinor("1.001"),/two decimal/)});
test("default chart is explicit and cannot be duplicated",()=>{const s=chart();assert.ok(s.accounts.length>30);assert.throws(()=>createDefaultChart(s,C,B),/already exists/)});
test("unbalanced and malformed journals are rejected",()=>{const s=chart(),cash=id(s,"Cash"),capital=id(s,"Owner Capital");assert.throws(()=>saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Journal Voucher",narration:"Bad",lines:[{accountId:cash,debit:100},{accountId:capital,credit:99}]}),/unbalanced/);assert.throws(()=>saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Journal Voucher",narration:"Bad",lines:[{accountId:cash,debit:100,credit:10},{accountId:capital,credit:90}]}),/either Debit or Credit/)});
test("balanced draft posts and updates general ledger",()=>{let s=chart(),cash=id(s,"Cash"),capital=id(s,"Owner Capital"),r=saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Opening Balance Voucher",narration:"Opening capital",authorisedControlAdjustment:true,lines:[{accountId:cash,debit:1000},{accountId:capital,credit:1000}]});s=postJournal(r.state,r.record.id).state;assert.equal(ledger(s,{companyId:C,accountId:cash}).at(-1).balanceMinor,100000);assert.equal(s.journals[0].status,"Posted")});
test("source posting key is idempotent",()=>{let s=chart(),ar=id(s,"Accounts Receivable"),sales=id(s,"Sales Revenue"),source={module:"Sales",entityType:"Invoice",entityId:"INV-1",eventVersion:1,documentNumber:"INV-1",postingRuleId:"RULE-SALES-INVOICE"},r=saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Sales Voucher",narration:"Invoice",source,lines:[{accountId:ar,debit:100},{accountId:sales,credit:100}]});s=postJournal(r.state,r.record.id).state;r=saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Sales Voucher",narration:"Duplicate",source,lines:[{accountId:ar,debit:100},{accountId:sales,credit:100}]});assert.throws(()=>postJournal(r.state,r.record.id),/already posted/)});
test("posted journals reverse with a separate opposite journal",()=>{let s=chart(),cash=id(s,"Cash"),capital=id(s,"Owner Capital"),r=saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Journal Voucher",narration:"Capital",authorisedControlAdjustment:true,lines:[{accountId:cash,debit:100},{accountId:capital,credit:100}]});s=postJournal(r.state,r.record.id).state;const original=r.record.id,rev=reverseJournal(s,original,"2026-08-02","Correction");assert.equal(rev.state.journals.find(x=>x.id===original).status,"Reversed");assert.equal(rev.record.voucherType,"Reversal Voucher");assert.equal(ledger(rev.state,{companyId:C,accountId:cash}).at(-1).balanceMinor,0)});
test("trial balance and balance sheet expose exact differences",()=>{let s=chart(),cash=id(s,"Cash"),capital=id(s,"Owner Capital"),r=saveDraft(s,{companyId:C,branchId:B,postingDate:"2026-08-01",voucherType:"Journal Voucher",narration:"Capital",authorisedControlAdjustment:true,lines:[{accountId:cash,debit:500},{accountId:capital,credit:500}]});s=postJournal(r.state,r.record.id).state;const tb=trialBalance(s,{companyId:C,start:"2026-08-01",end:"2026-08-31"}),st=statements(s,{companyId:C,start:"2026-08-01",end:"2026-08-31"});assert.equal(tb.difference,0);assert.equal(tb.balanced,true);assert.equal(st.balanceSheet.difference,0)});
