import test from"node:test";import assert from"node:assert/strict";
import fs from"node:fs";import zlib from"node:zlib";
import{detectMapping,detectMarketplace,detectReportType,normalizeRows,isMeeshoReport,normalizeMeeshoRows,validateTransactions,importStatus,consolidate,filingReadiness,gstr1Json,transactionKey}from"../src/gst/ecommerce-core.js";
function unzip(buf){const v=new DataView(buf.buffer,buf.byteOffset,buf.byteLength);let e=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-65557);i--)if(v.getUint32(i,true)===0x06054b50){e=i;break}const count=v.getUint16(e+10,true),off=v.getUint32(e+16,true),out={};let p=off;for(let n=0;n<count;n++){const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),nl=v.getUint16(p+28,true),xl=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),local=v.getUint32(p+42,true),name=buf.subarray(p+46,p+46+nl).toString(),ln=v.getUint16(local+26,true),le=v.getUint16(local+28,true),start=local+30+ln+le,packed=buf.subarray(start,start+size);out[name]=method===0?packed:zlib.inflateRawSync(packed);p+=46+nl+xl+cl}return out}
const xmlText=s=>String(s||"").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&");
function xlsxRows(buf){const z=unzip(buf),shared=z["xl/sharedStrings.xml"]?[...z["xl/sharedStrings.xml"].toString().matchAll(/<si[^>]*>([\s\S]*?)<\/si>/g)].map(m=>xmlText(m[1])):[],xml=z["xl/worksheets/sheet1.xml"].toString(),matrix=[];for(const rm of xml.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)){const vals=[];for(const cm of rm[1].matchAll(/<c([^>]*)>([\s\S]*?)<\/c>/g)){const ref=(cm[1].match(/r="([A-Z]+)\d+"/)||[])[1]||"A";let col=0;for(const c of ref)col=col*26+c.charCodeAt(0)-64;while(vals.length<col)vals.push("");const type=(cm[1].match(/t="([^"]+)"/)||[])[1],raw=(cm[2].match(/<v[^>]*>([\s\S]*?)<\/v>/)||cm[2].match(/<is[^>]*>([\s\S]*?)<\/is>/)||[])[1]||"";vals[col-1]=type==="s"?shared[+raw]:xmlText(raw)}matrix.push(vals)}const headers=matrix.shift();return matrix.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??""])))}
function realMeeshoFixture(){const files=unzip(fs.readFileSync("reference-files/gst_4251941_6_2026.zip")),parts=[];for(const[fileName,bytes]of Object.entries(files)){const rows=xlsxRows(bytes),kind=/return/.test(fileName)?"returns":"sales";parts.push({fileName,sheetName:"4251941",kind,rows,normalized:normalizeMeeshoRows({rows,fileName,sheetName:"4251941",kind})})}const checked=validateTransactions(parts.flatMap(x=>x.normalized),{filingPeriod:"2026-06",supplierGstin:"33EGPPM1683E1Z8"});return{parts,checked,stats:importStatus(checked),summary:consolidate(checked)}}
const base={"Invoice Number":"INV-1","Invoice Date":"2026-08-10","Place of Supply":"27-Maharashtra","HSN Code":"6109","GST Rate":"18","Taxable Amount":"1000",IGST:"0",CGST:"90",SGST:"90","Order ID":"ORD-1","Transaction Type":"Sale"};
const normalize=(rows=[base],marketplace="Meesho",report={type:"Sales",sales:true,returns:false})=>{const mapping=detectMapping(Object.keys(rows[0])).mapping;return normalizeRows({rows,mapping,marketplace,fileName:"report.xlsx",sheetName:"GST",reportType:report})};
const valid=rows=>validateTransactions(rows,{filingPeriod:"2026-08"});
test("Meesho signatures and separate sales/return reports",()=>{assert.equal(detectMarketplace({headers:["Sub Order No","Supplier GSTIN"],fileName:"tcs_sales.xlsx"}).marketplace,"Meesho");assert.equal(detectReportType({fileName:"tcs_sales_return.xlsx",headers:Object.keys(base)}).returns,true)});
test("Flipkart mixed sales and returns normalize per transaction",()=>{const rows=[base,{...base,"Invoice Number":"CN-1","Transaction Type":"Return","Original Invoice No":"INV-1"}],report=detectReportType({fileName:"flipkart.xlsx",sheetName:"Sales and Returns",headers:Object.keys(rows[1]),rows}),out=normalize(rows,"Flipkart",report);assert.equal(out[0].documentType,"Invoice");assert.equal(out[1].documentType,"Credit Note");assert.equal(out[1].taxableValue,-1000)});
test("Amazon schema synonyms map automatically",()=>{const headers=["Amazon Order ID","Tax Invoice Number","Tax Invoice Date","Ship State","HSN/SAC","Tax %","Net Taxable Value","Integrated Tax"];const m=detectMapping(headers).mapping;assert.equal(m.orderId,"Amazon Order ID");assert.equal(m.invoiceNumber,"Tax Invoice Number");assert.equal(m.taxableValue,"Net Taxable Value")});
test("generic marketplace requires source confirmation",()=>assert.equal(detectMarketplace({headers:Object.keys(base),selected:["Amazon","Flipkart"]}).confidence,"Needs Review"));
test("multi-marketplace transactions consolidate into one return",()=>{const rows=valid([...normalize([base],"Meesho"),...normalize([{...base,"Invoice Number":"F-1","Order ID":"F-1"}],"Flipkart"),...normalize([{...base,"Invoice Number":"A-1","Order ID":"A-1"}],"Amazon")]);assert.equal(consolidate(rows).active.length,3)});
test("valid return reduces values and matches sale",()=>{const sale=normalize()[0],ret=normalize([{...base,"Invoice Number":"CN-1","Transaction Type":"Return","Original Invoice No":"INV-1"}],"Meesho",{type:"Return / Credit Note",returns:true})[0],rows=valid([sale,ret]);assert.equal(rows[1].taxableValue,-1000);assert.notEqual(rows[1].validation.severity,"Needs Review")});
test("duplicate transaction key prevents double counting",()=>{const first=valid(normalize())[0],second=validateTransactions(normalize(),{filingPeriod:"2026-08",existing:[first]})[0];assert.equal(transactionKey(first),transactionKey(second));assert.equal(second.duplicate,true)});
test("valid buyer GSTIN creates B2B",()=>{const rows=valid(normalize([{...base,"Buyer GSTIN":"27ABCDE1234F1Z5"}]));assert.equal(consolidate(rows).b2b.length,1)});
test("blank buyer GSTIN creates B2C",()=>assert.equal(consolidate(valid(normalize())).b2c.length,1));
test("interstate IGST remains distinct",()=>{const rows=valid(normalize([{...base,IGST:"180",CGST:"0",SGST:"0","State Code":"29"}]));assert.equal(rows[0].igst,180);assert.equal(rows[0].cgst,0)});
test("intrastate CGST and SGST remain balanced",()=>{const row=valid(normalize())[0];assert.equal(row.cgst,90);assert.equal(row.sgst,90);assert.notEqual(row.validation.severity,"Error")});
test("missing HSN is Needs Review and never fabricated",()=>{const x={...base};delete x["HSN Code"];const row=valid(normalize([x]))[0];assert.equal(row.hsn,"");assert.equal(row.validation.severity,"Needs Review")});
test("invalid GSTIN is an Error",()=>assert.equal(valid(normalize([{...base,"Buyer GSTIN":"BADGSTIN"}]))[0].validation.severity,"Error"));
test("missing POS requires review",()=>{const x={...base};delete x["Place of Supply"];assert.equal(valid(normalize([x]))[0].validation.severity,"Needs Review")});
test("credit and debit notes are classified as adjustments",()=>{const credit=normalize([{...base,"Invoice Number":"CN-1","Transaction Type":"Credit Note"}],"Amazon",{type:"Mixed",returns:true})[0],debit=normalize([{...base,"Invoice Number":"DN-1","Transaction Type":"Debit Note"}],"Amazon",{type:"Mixed",debit:true})[0],c=consolidate(valid([credit,debit]));assert.equal(c.notes.length,2);assert.deepEqual(c.notes.map(x=>x.documentType),["Credit Note","Debit Note"])});
test("nil exempt and non-GST remain separate",()=>{const rows=valid(normalize([{...base,"Invoice Number":"N-1","Supply Nature":"Nil Rated"},{...base,"Invoice Number":"E-1","Supply Nature":"Exempt"},{...base,"Invoice Number":"G-1","Supply Nature":"Non GST"}]));const c=consolidate(rows);assert.equal(c.nil.length,1);assert.equal(c.exempt.length,1);assert.equal(c.nonGst.length,1)});
test("filing JSON is blocked until schema and row checks are verified",()=>{const unverified={gstin:"27ABCDE1234F1Z5",filingPeriod:"2026-08"},rows=valid(normalize());assert.equal(filingReadiness(rows,unverified).ready,false);assert.throws(()=>gstr1Json(rows,unverified),/schema fixture verification/);const setup={...unverified,schemaVerified:true};assert.equal(filingReadiness(rows,setup).ready,true);const json=gstr1Json(rows,setup);assert.equal(json.gstin,setup.gstin);assert.equal(json.fp,"082026");assert.equal(json.b2cs.length,1);const bad=valid(normalize([{...base,"Invoice Number":""}]));assert.throws(()=>gstr1Json(bad,setup),/Not Ready/)});
test("real Meesho reference ZIP parses both actual workbooks and 89 transactions",()=>{const f=realMeeshoFixture();assert.deepEqual(f.parts.map(x=>x.fileName).sort(),["tcs_sales.xlsx","tcs_sales_return.xlsx"]);assert.ok(f.parts.every(x=>isMeeshoReport(Object.keys(x.rows[0]))));assert.equal(f.parts.find(x=>x.kind==="sales").rows.length,74);assert.equal(f.parts.find(x=>x.kind==="returns").rows.length,15);assert.equal(f.checked.length,89);assert.equal(f.stats.error,0);assert.equal(f.stats.review,0);assert.equal(f.summary.b2c.length,89);assert.ok(f.summary.hsn.length>0)});
test("real Meesho package supports Excel review but blocks JSON without invoice series",()=>{const f=realMeeshoFixture(),ready=filingReadiness(f.checked,{gstin:"33EGPPM1683E1Z8",filingPeriod:"2026-06",schemaVerified:true});assert.equal(f.summary.active.length,89);assert.equal(ready.ready,false);assert.ok(ready.missing.includes("Documents Issued / invoice series confirmation"))});
