import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { employeeImportErrorRows, employeeTemplateHeaders, validateEmployeeImportRows } from "../src/hr-payroll/employee-import.js";
import { companyExportBranding, countryCurrencyFormat, INFOBRIDGE_FOOTER } from "../src/export/workbook.js";
import { eligibleSalesEmployees } from "../src/sales/employees.js";

const departments=[{id:"DEP-SALES",name:"Sales & CRM",active:true},{id:"DEP-HOUSE",name:"House Keeping",active:true},{id:"DEP-SERVICE",name:"SERVICE",active:true},{id:"DEP-OLD",name:"Old Team",active:false}];
const common=(id="EMP-001")=>({"Employee ID":id,"First Name":"Ahmed","Last Name":"Khan",Email:`${id.toLowerCase()}@example.com`,Mobile:"+971500000000",Nationality:"Indian",Department:"Sales & CRM",Designation:"Sales Manager","Date of Joining":"2026-08-01","Employment Type":"Fixed Term","Employment Status":"Active"});
const uae=id=>({...common(id),Emirate:"Dubai","Basic Salary AED":"12000","Housing Allowance":"2000","Transport Allowance":"500","Other Allowances":"250","Emirates ID":"784-0000-0000000-0","Work Permit Number":"WP1","Visa Number":"V1","Visa Expiry Date":"2027-01-01","Work Permit Expiry Date":"2027-01-01","Salary Payment Method":"Bank Transfer","Bank Name":"Bank","Account Holder Name":"Ahmed Khan","Account Number":"001",IBAN:"AE070000000000000000001"});
const india=id=>({...common(id),"Work Location":"Mumbai","Basic Salary INR":"50000",HRA:"20000","Other Allowances":"5000",PAN:"ABCDE1234F",UAN:"UAN1","PF Applicable":"Yes","ESI Applicable":"No","Professional Tax Applicable":"Yes","Salary Payment Method":"Bank Transfer","Bank Name":"Bank","Account Holder Name":"Ahmed Khan","Bank Account Number":"001","IFSC Code":"ABCD000001"});
const validate=(rows,country,extra={})=>validateEmployeeImportRows(rows,{country,departments,existingEmployees:[],createId:(()=>{let id=0;return()=>`STABLE-${++id}`})(),...extra});

test("India and UAE templates contain only their jurisdiction fields",()=>{const ind=employeeTemplateHeaders("IN"),ae=employeeTemplateHeaders("AE");for(const key of["Basic Salary INR","HRA","PAN","UAN","PF Applicable","IFSC Code"])assert.ok(ind.includes(key));for(const key of["Basic Salary AED","Housing Allowance","Transport Allowance","Emirates ID","Work Permit Number","IBAN"])assert.ok(ae.includes(key));for(const key of["Emirates ID","IBAN","Basic Salary AED"])assert.ok(!ind.includes(key));for(const key of["PAN","UAN","PF Applicable","IFSC Code"])assert.ok(!ae.includes(key))});
test("valid India and UAE imports use one stable employee model",()=>{const [inResult]=validate([india("IN-1")],"IN"),[aeResult]=validate([uae("AE-1")],"AE");assert.equal(inResult.valid,true);assert.equal(aeResult.valid,true);assert.deepEqual([inResult.record.countryCode,inResult.record.currency],["IN","INR"]);assert.deepEqual([aeResult.record.countryCode,aeResult.record.currency],["AE","AED"]);assert.equal(inResult.record.departmentId,"DEP-SALES");assert.equal(aeResult.record.departmentId,"DEP-SALES")});
test("India and UAE imports accept active custom Administration departments by stable ID",()=>{const indiaRow=india("IN-HOUSE"),uaeRow=uae("AE-SERVICE");indiaRow.Department="House Keeping";uaeRow.Department="SERVICE";const[inResult]=validate([indiaRow],"IN"),[aeResult]=validate([uaeRow],"AE");assert.deepEqual([inResult.valid,inResult.record.departmentId],[true,"DEP-HOUSE"]);assert.deepEqual([aeResult.valid,aeResult.record.departmentId],[true,"DEP-SERVICE"])});
test("inactive or unknown departments are rejected with Administration guidance",()=>{for(const name of["Old Team","Kitchen ABC"]){const row=uae("AE-2");row.Department=name;const[result]=validate([row],"AE");assert.equal(result.valid,false);assert.match(result.errors.map(e=>e.message).join(" "),/Department not found or inactive.*Administration → Departments/)}});
test("duplicates invalid email dates salary emirate and employment type are reported by row",()=>{const bad=uae("DUP");bad.Email="bad";bad["Date of Joining"]="2026-99-01";bad["Basic Salary AED"]="x";bad.Emirate="Kerala";bad["Employment Type"]="Unknown";const results=validate([bad,bad],"AE",{existingEmployees:[{employeeId:"DUP"}]});assert.ok(results.every(row=>!row.valid));const text=results.flatMap(row=>row.errors.map(e=>e.message)).join(" ");assert.match(text,/already exists|duplicated/);assert.match(text,/Email is invalid/);assert.match(text,/valid YYYY-MM-DD/);assert.match(text,/non-negative number/);assert.match(text,/Emirate.*invalid/);assert.match(text,/Employment type.*invalid/);assert.ok(employeeImportErrorRows(results).every(row=>row["Original row"]>=2))});
test("large valid mixed-country batches retain unique employee identities",()=>{let inId=0,aeId=0;const inRows=validate(Array.from({length:45},(_,i)=>india(`IN-${i}`)),"IN",{createId:()=>`IN-STABLE-${++inId}`}),aeRows=validate(Array.from({length:45},(_,i)=>uae(`AE-${i}`)),"AE",{createId:()=>`AE-STABLE-${++aeId}`}),records=[...inRows,...aeRows].map(row=>row.record);assert.equal(records.filter(Boolean).length,90);assert.equal(new Set(records.map(row=>row.id)).size,90);assert.equal(eligibleSalesEmployees(records,departments).length,90)});
test("shared workbook branding resolves current company logo name footer and country currency",()=>{const withLogo=companyExportBranding({companyId:"CO1",legalName:"Shayay Hospitality Services",logo:"data:image/png;base64,AAAA"}),withoutLogo=companyExportBranding({name:"Another Company"});assert.equal(withLogo.companyName,"Shayay Hospitality Services");assert.match(withLogo.logo,/data:image\/png/);assert.equal(withoutLogo.logo,"");assert.equal(INFOBRIDGE_FOOTER,"Generated with InfoBridgeIndia");assert.match(countryCurrencyFormat("IN"),/₹/);assert.match(countryCurrencyFormat("AE"),/AED/)});
test("Employees UI exposes explicit country actions filters and branded templates",()=>{const source=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8");for(const label of["Add India Employee","Import India Employees","Add UAE Employee","Import UAE Employees","Download India Employee Template","Download UAE Employee Template"])assert.match(source,new RegExp(label));assert.match(source,/data-employee-country-filter/);assert.match(source,/brandedWorkbook/);assert.match(source,/countryCode/);assert.match(source,/employeeImportCountry/)});
