import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
import{availableLeaveTypes,employeeLeaveBalances,leaveApplicationDays,STANDARD_LEAVE_TYPES,validateLeaveApplication}from"../src/hr-payroll/leave.js";
import{payrollForEmployee}from"../src/hr-payroll/core.js";
import{lockedPayrollForLeave}from"../src/hr-payroll/leave-payroll-lock.js";

const employee={id:"INTERNAL-1",employeeId:"EMP-001",firstName:"Ahmed",lastName:"Khan",basicSalary:27000,weeklyOffType:"one",weeklyOffDays:["Sunday"]},settings={};
test("pending and rejected leave do not reduce configured leave balances",()=>{const type={id:"MED",name:"Medical Leave",paymentType:"paid",allowedDays:15,status:"active"},applications=[{id:"L1",employeeId:employee.id,leaveTypeId:"MED",from:"2026-07-01",to:"2026-07-03",status:"pending"},{id:"L2",employeeId:employee.id,leaveTypeId:"MED",from:"2026-07-06",to:"2026-07-08",status:"rejected"}];assert.deepEqual(employeeLeaveBalances(employee,[type],applications,settings)[0],{leaveTypeId:"MED",name:"Medical Leave",paymentType:"paid",allowed:15,used:0,available:15,active:true})});
test("approved three-day paid leave reduces balance and satisfies payroll attendance",()=>{const type={id:"MED",name:"Medical Leave",paymentType:"paid",allowedDays:15,status:"active"},leave={id:"L1",employeeId:employee.id,leaveTypeId:"MED",leaveTypeName:"Medical Leave",paid:true,from:"2026-07-01",to:"2026-07-03",status:"approved"};assert.equal(leaveApplicationDays(leave,employee,settings).length,3);assert.equal(employeeLeaveBalances(employee,[type],[leave],settings)[0].available,12);const attendance=[];const payroll=payrollForEmployee(employee,{attendance,leaves:[leave],from:"2026-07-01",to:"2026-07-03"});assert.equal(payroll.paidLeaveDays,3);assert.equal(payroll.lopDays,0);assert.equal(payroll.missingDays,0)});
test("approved unpaid leave is recognized and flows through existing LOP deduction",()=>{const leave={id:"L2",employeeId:employee.id,leaveTypeId:"UNPAID",leaveTypeName:"Unpaid Leave",paid:false,from:"2026-07-01",to:"2026-07-03",status:"approved"},payroll=payrollForEmployee(employee,{attendance:[],leaves:[leave],from:"2026-07-01",to:"2026-07-03"});assert.equal(payroll.paidLeaveDays,0);assert.equal(payroll.unpaidLeaveDays,3);assert.equal(payroll.lopDays,3);assert.equal(payroll.missingDays,0);assert.ok(payroll.lopDeduction>0)});
test("fixed entitlement blocks requests beyond available approved balance",()=>{const type={id:"MED",name:"Medical Leave",paymentType:"paid",allowedDays:3,status:"active"},existing={id:"OLD",employeeId:employee.id,leaveTypeId:"MED",from:"2026-07-01",to:"2026-07-02",status:"approved"};assert.throws(()=>validateLeaveApplication({application:{from:"2026-07-06",to:"2026-07-08"},employee,type,applications:[existing]}),/exceeds the available balance/)});
test("Leave Application provides the complete standard catalogue with Vacation first",()=>{assert.deepEqual(STANDARD_LEAVE_TYPES.map(type=>type.name),["Vacation","Casual Leave","Sick Leave","Medical Leave","Emergency Leave","Unpaid Leave","Maternity Leave","Paternity / Parental Leave","Other Leave"]);assert.equal(STANDARD_LEAVE_TYPES.find(type=>type.name==="Vacation").paymentType,"paid");assert.equal(STANDARD_LEAVE_TYPES.find(type=>type.name==="Unpaid Leave").paymentType,"unpaid");assert.equal(STANDARD_LEAVE_TYPES.find(type=>type.name==="Other Leave").paymentSelectable,true)});
test("configured duplicate names do not duplicate standard dropdown options",()=>{const types=availableLeaveTypes([{id:"OLD",name:"Casual Leave",allowedDays:12},{id:"CUSTOM",name:"Bereavement Leave"}]);assert.equal(types.filter(type=>type.name==="Casual Leave").length,1);assert.equal(types.some(type=>type.name==="Bereavement Leave"),true)});
test("approved Vacation follows attendance payroll and payslip snapshot data",()=>{const vacation=STANDARD_LEAVE_TYPES[0],application={id:"VAC-1",employeeId:employee.id,leaveTypeId:vacation.id,from:"2026-08-24",to:"2026-08-27",status:"approved"},validated=validateLeaveApplication({application,employee,type:vacation}),saved={...application,...validated},payroll=payrollForEmployee(employee,{attendance:[],leaves:[saved],from:"2026-08-24",to:"2026-08-27"});assert.equal(saved.leaveTypeName,"Vacation");assert.equal(saved.days,4);assert.equal(payroll.paidLeaveDays,4);assert.equal(payroll.missingDays,0);assert.deepEqual(payroll.leaveBreakdown,{Vacation:4})});
test("Leave page is operational and does not render the all-employee Current balances table",()=>{const source=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8");for(const label of["On Leave Today","Pending Requests","Approved This Month","Unpaid Leave This Month","Leave Application","Leave Requests"])assert.match(source,new RegExp(label));assert.doesNotMatch(source,/table\("Current balances"/);assert.match(source,/id="leave-application-form"/);assert.match(source,/data-leave-search/);assert.match(source,/leaveStatusFilter/);assert.match(source,/pageSize=10/)});
test("inline leave form calculates days from employee weekly offs",()=>{const fridayEmployee={...employee,weeklyOffDays:["Friday"]},dates=leaveApplicationDays({from:"2026-08-23",to:"2026-08-27"},fridayEmployee);assert.equal(dates.length,5);const sundayEmployee={...employee,weeklyOffDays:["Sunday"]};assert.equal(leaveApplicationDays({from:"2026-08-23",to:"2026-08-27"},sundayEmployee).length,4)});
test("Leave Requests uses one Edit action and the inline form preserves the edited stable ID",()=>{const source=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8");assert.match(source,/action=`<button class="text-button" data-edit-leave=/);assert.doesNotMatch(source,/action=item\.status===/);assert.match(source,/editing\?"Edit Leave Application":"Leave Application"/);assert.match(source,/editing\?"Update Leave":"Save"/);assert.match(source,/data-cancel-leave-edit/);assert.match(source,/id:old\?\.id\|\|uid\("LEV"\)/)});
test("approved leave overlapping a locked payroll is protected",()=>{const leave={id:"L-LOCK",employeeId:employee.id,employeeCode:employee.employeeId,from:"2026-08-24",to:"2026-08-27",status:"approved"},locked={id:"PAY-1",period:"2026-08",status:"approved",items:[{employeeId:employee.id,employeeCode:employee.employeeId}]};assert.equal(lockedPayrollForLeave(leave,[locked],employee),locked);assert.equal(lockedPayrollForLeave({...leave,status:"pending"},[locked],employee),null);assert.equal(lockedPayrollForLeave(leave,[{...locked,status:"draft"}],employee),null)});
test("editing approved leave remains available while the overlapping payroll is draft",()=>{const leave={id:"L-DRAFT",employeeId:employee.id,from:"2026-08-24",to:"2026-08-27",status:"approved"},draft={id:"PAY-DRAFT",from:"2026-08-01",to:"2026-08-31",status:"draft",items:[{employeeId:employee.id}]};assert.equal(lockedPayrollForLeave(leave,[draft],employee),null);const changed={...leave,to:"2026-08-28"},payroll=payrollForEmployee(employee,{attendance:[],leaves:[changed],from:"2026-08-24",to:"2026-08-28"});assert.equal(payroll.paidLeaveDays,5);assert.equal(payroll.missingDays,0)});
