import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";
import{reportCsv,reportMonthLabel,summarizeHrReport}from"../src/hr-payroll/reports.js";

const records={
  employees:[{id:"E1",departmentId:"D1",active:true},{id:"E2",departmentId:"D2",active:true},{id:"E3",departmentId:"D1",active:false}],
  departments:[{id:"D1",name:"Finance & Accounts"},{id:"D2",name:"Human Resources"}],
  attendance:[{date:"2026-08-01",status:"present"},{date:"2026-08-02",status:"absent"},{date:"2026-08-03",status:"late"},{date:"2026-07-01",status:"present"},{date:"2026-07-02",status:"present"}],
  payrollRuns:[{period:"2026-08",status:"approved",totalNet:362644.46},{period:"2026-08",status:"draft",totalNet:900000},{period:"2026-07",status:"approved",totalNet:120000}],
  leaveTypes:[{id:"VAC",name:"Vacation"},{id:"SICK",name:"Sick Leave"}],
  leaveTransactions:[{leaveTypeId:"VAC",from:"2026-07-31",to:"2026-08-02",status:"approved"},{leaveTypeId:"VAC",from:"2026-08-10",to:"2026-08-12",status:"pending"},{leaveTypeId:"SICK",dates:["2026-07-04","2026-08-04"],status:"approved"},{leaveTypeId:"SICK",from:"2026-08-20",to:"2026-08-20",status:"rejected"}]
};

test("report summary isolates attendance payroll and approved leave to the selected month",()=>{const august=summarizeHrReport({period:"2026-08",...records});assert.equal(august.periodLabel,"August 2026");assert.deepEqual({headcount:august.headcount,presentDays:august.presentDays,absentDays:august.absentDays,approvedPayroll:august.approvedPayroll},{headcount:2,presentDays:1,absentDays:1,approvedPayroll:362644.46});assert.deepEqual(august.departments,[{department:"Finance & Accounts",count:1},{department:"Human Resources",count:1}]);assert.deepEqual(august.leaves,[{type:"Vacation",taken:2},{type:"Sick Leave",taken:1}])});
test("selecting a previous month refreshes only period-dependent figures",()=>{const july=summarizeHrReport({period:"2026-07",...records});assert.equal(reportMonthLabel("2026-07"),"July 2026");assert.equal(july.headcount,2);assert.equal(july.presentDays,2);assert.equal(july.absentDays,0);assert.equal(july.approvedPayroll,120000);assert.deepEqual(july.leaves,[{type:"Vacation",taken:1},{type:"Sick Leave",taken:1}])});
test("report CSV identifies and exports the visible report period",()=>{const summary=summarizeHrReport({period:"2026-08",...records}),csv=reportCsv(summary,{companyName:"InfoBridgeIndia",currency:"AED"});for(const value of["Report Month","August 2026","2026-08","Approved Payroll","362644.46","Finance & Accounts","Vacation"])assert.match(csv,new RegExp(value.replace(/[&]/g,"\\&")))});
test("Dashboard defaults reporting to the current month and uses unclipped responsive tables",()=>{const app=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8"),css=readFileSync(new URL("../src/hr-payroll/styles.css",import.meta.url),"utf8");assert.match(app,/let reportPeriod=month\(\)/);assert.match(app,/type="month" data-report-period/);assert.doesNotMatch(app,/<span>Attendance records<\/span>/);assert.match(css,/\.report-table\{min-width:0;table-layout:fixed\}/);assert.match(css,/@media\(max-width:1050px\)\{\.report-grid\{grid-template-columns:1fr\}\}/)});
test("Dashboard owns the shared month selector CSV export and report summaries",()=>{const app=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8"),dashboard=app.slice(app.indexOf("function dashboard()"),app.indexOf("function employees()"));assert.match(dashboard,/summary=reportSummary\(\)/);assert.match(dashboard,/data-report-period/);assert.match(dashboard,/data-export-report/);assert.match(dashboard,/reportTable\("Department Headcount",summary\.departments/);assert.match(dashboard,/reportTable\("Leave Summary",summary\.leaves/);assert.match(dashboard,/filter\(\(?run=>run\.status==="approved"\)?\)/);assert.doesNotMatch(dashboard,/Recent employees/i);assert.match(app,/function reports\(\)\{return dashboard\(\)\}/)});
test("Reports is absent from the HR sidebar",()=>{const app=readFileSync(new URL("../src/hr-payroll/app.js",import.meta.url),"utf8"),shell=app.slice(app.indexOf("function shell("),app.indexOf("function setup("));assert.doesNotMatch(shell,/\["reports","Reports"\]/)});
