import test from"node:test";import assert from"node:assert/strict";
import{initialState,saveLead,moveLead,convertLeadToCustomer,saveQuotation,convertQuotationToOrder,convertOrderToInvoice,recordPayment,createReturn,customerBalance,dashboardMetrics,documentTotals,financialYear,deleteLead}from"../src/sales/core.js";
function connected(){let state=initialState();state.settings.sellerStateCode="33";let r=saveLead(state,{name:"Acme Traders",mobile:"9876543210",email:"sales@acme.test",stage:"Qualified",priority:"High",expectedValue:11800,interest:"Consulting"});state=r.state;const lead=r.record;state=moveLead(state,lead.id,"Won");r=convertLeadToCustomer(state,lead.id);state=r.state;const customer=r.record;r=saveQuotation(state,{customerId:customer.id,leadId:lead.id,date:"2026-08-19",validUntil:"2026-08-31",placeOfSupply:"33",status:"Accepted",items:[{description:"Consulting",hsnSac:"9983",quantity:1,unit:"Service",rate:10000,discount:0,gstRate:18}]});state=r.state;const quote=r.record;r=convertQuotationToOrder(state,quote.id);state=r.state;const order=r.record;r=convertOrderToInvoice(state,order.id);state=r.state;return{state,lead,customer,quote,order,invoice:r.record}}
test("same-state GST uses CGST and SGST only",()=>{const x=documentTotals([{description:"A",quantity:2,rate:1000,discount:10,gstRate:18}],{sellerStateCode:"33"},"33");assert.equal(x.taxable,1800);assert.equal(x.cgst,162);assert.equal(x.sgst,162);assert.equal(x.igst,0);assert.equal(x.grandTotal,2124)});
test("interstate GST uses IGST only",()=>{const x=documentTotals([{description:"A",quantity:1,rate:10000,discount:0,gstRate:18}],{sellerStateCode:"33"},"27");assert.equal(x.cgst,0);assert.equal(x.sgst,0);assert.equal(x.igst,1800);assert.equal(x.grandTotal,11800)});
test("lead to invoice preserves source references and blocks duplicate conversions",()=>{const{state,lead,customer,quote,order,invoice}=connected();assert.equal(state.leads.find(x=>x.id===lead.id).customerId,customer.id);assert.equal(state.quotations.find(x=>x.id===quote.id).orderId,order.id);assert.equal(state.orders.find(x=>x.id===order.id).invoiceId,invoice.id);assert.equal(invoice.orderId,order.id);const again=convertOrderToInvoice(state,order.id);assert.equal(again.duplicate,true);assert.equal(again.state.invoices.length,1)});
test("partial payment updates paid, balance, status, customer statement and dashboard",()=>{let{state,customer,invoice}=connected();let r=recordPayment(state,{customerId:customer.id,invoiceId:invoice.id,date:"2026-08-19",amount:6000,mode:"UPI"});state=r.state;const saved=state.invoices[0];assert.equal(saved.amountPaid,6000);assert.equal(saved.balanceDue,5800);assert.equal(saved.status,"Partially Paid");assert.equal(customerBalance(state,customer.id),5800);assert.equal(dashboardMetrics(state,new Date("2026-08-19T12:00:00Z")).monthCollected,6000);assert.throws(()=>recordPayment(state,{customerId:customer.id,invoiceId:invoice.id,date:"2026-08-19",amount:6000,mode:"Cash"}),/exceeds outstanding/)});
test("credit note prevents impossible return quantities",()=>{let{state,invoice}=connected();let r=createReturn(state,{invoiceId:invoice.id,date:"2026-08-19",reason:"Service adjustment",items:[{description:"Consulting",quantity:0.5}]});state=r.state;assert.equal(r.record.grandTotal,5900);assert.throws(()=>createReturn(state,{invoiceId:invoice.id,date:"2026-08-20",reason:"Again",items:[{description:"Consulting",quantity:0.6}]}),/exceeds/)});
test("connected leads cannot be accidentally deleted",()=>{const{state,lead}=connected();assert.throws(()=>deleteLead(state,lead.id),/Archive/)});
test("financial year numbering boundary is India-aware",()=>{assert.equal(financialYear("2026-03-31"),"2025-26");assert.equal(financialYear("2026-04-01"),"2026-27")});
