export const STAGES=["New Lead","Contacted","Qualified","Quotation Sent","Negotiation","Won","Lost"];
export const ACTIVITY_TYPES=["Call","WhatsApp","Email","Meeting","Task","Note"];
export const today=()=>new Date().toISOString().slice(0,10);
export const uid=(prefix)=>`${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
export const num=v=>Number.isFinite(Number(v))?Number(v):0;
export const round=v=>Math.round((num(v)+Number.EPSILON)*100)/100;
export const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(num(v));
export const financialYear=(date=today())=>{const d=new Date(`${date}T00:00:00`),y=d.getFullYear();return d.getMonth()>=3?`${y}-${String(y+1).slice(2)}`:`${y-1}-${String(y).slice(2)}`};
export function initialState(){return{version:1,settings:{company:"InfoBridgeIndia Business",branch:"Head Office",sellerStateCode:"33",invoicePrefix:"INV",bankDetails:""},sequences:{},leads:[],customers:[],activities:[],quotations:[],orders:[],invoices:[],payments:[],returns:[],team:[],services:[],audit:[]}}
const clone=x=>structuredClone(x); const stamp=()=>new Date().toISOString();
export function nextNumber(state,type,date=today()){const fy=financialYear(date),key=`${type}:${fy}`;state.sequences[key]=num(state.sequences[key])+1;const prefixes={lead:"LEAD",customer:"CUS",quotation:"QT",order:"SO",invoice:state.settings.invoicePrefix||"INV",payment:"RCT",credit:"CN"};return `${prefixes[type]}/${fy}/${String(state.sequences[key]).padStart(4,"0")}`}
export function lineTotals(line,sellerStateCode,placeOfSupply){const quantity=num(line.quantity),rate=num(line.rate),discount=num(line.discount);if(quantity<=0)throw Error("Quantity must be greater than zero");if(rate<0||discount<0||discount>100)throw Error("Enter a valid rate and discount");const gross=quantity*rate,taxable=round(gross-gross*discount/100),gstRate=num(line.gstRate);const tax=round(taxable*gstRate/100),same=String(sellerStateCode)===String(placeOfSupply);return{...line,quantity,rate,discount,gstRate,taxable,cgst:same?round(tax/2):0,sgst:same?round(tax/2):0,igst:same?0:tax,total:round(taxable+tax)}}
export function documentTotals(lines,settings={},placeOfSupply,additionalCharges=0,roundOff=0){if(!lines?.length)throw Error("Add at least one line item");const items=lines.map(x=>lineTotals(x,settings.sellerStateCode,placeOfSupply));const sum=k=>round(items.reduce((a,x)=>a+num(x[k]),0));return{items,taxable:sum("taxable"),cgst:sum("cgst"),sgst:sum("sgst"),igst:sum("igst"),additionalCharges:num(additionalCharges),roundOff:num(roundOff),grandTotal:round(sum("total")+num(additionalCharges)+num(roundOff))}}
function required(data,fields){const missing=fields.filter(k=>!String(data[k]??"").trim());if(missing.length)throw Error(`Required: ${missing.join(", ")}`)}
function log(state,action,type,id,detail=""){state.audit.unshift({id:uid("AUD"),action,type,recordId:id,detail,createdAt:stamp()})}
export function saveLead(source,data){const state=clone(source);required(data,["name","mobile","stage"]);if(!/^\+?[0-9 -]{7,15}$/.test(data.mobile))throw Error("Enter a valid mobile number");const duplicate=state.leads.find(x=>x.id!==data.id&&!x.archived&&((data.mobile&&x.mobile===data.mobile)||(data.email&&x.email?.toLowerCase()===data.email.toLowerCase())));const now=stamp(),old=state.leads.find(x=>x.id===data.id);const lead={...old,...data,id:old?.id||nextNumber(state,"lead"),expectedValue:num(data.expectedValue),createdAt:old?.createdAt||now,updatedAt:now,archived:false,duplicateWarning:duplicate?`Possible duplicate: ${duplicate.id}`:""};if(old)state.leads[state.leads.indexOf(old)]=lead;else state.leads.unshift(lead);log(state,old?"Updated":"Created","Lead",lead.id);return{state,record:lead}}
export function archiveLead(source,id){const state=clone(source),x=state.leads.find(r=>r.id===id);if(!x)throw Error("Lead not found");x.archived=true;x.updatedAt=stamp();log(state,"Archived","Lead",id);return state}
export function deleteLead(source,id){const state=clone(source),x=state.leads.find(r=>r.id===id);if(!x)throw Error("Lead not found");if(state.quotations.some(q=>q.leadId===id)||state.orders.some(o=>o.leadId===id))throw Error("Archive this connected lead instead of deleting it");state.leads=state.leads.filter(r=>r.id!==id);state.activities=state.activities.filter(a=>a.relatedId!==id);log(state,"Deleted","Lead",id);return state}
export function moveLead(source,id,stage,lostReason=""){if(!STAGES.includes(stage))throw Error("Invalid pipeline stage");if(stage==="Lost"&&!lostReason.trim())throw Error("A lost reason is required");const state=clone(source),x=state.leads.find(r=>r.id===id);if(!x)throw Error("Lead not found");x.stage=stage;x.lostReason=stage==="Lost"?lostReason:"";x.updatedAt=stamp();log(state,"Stage changed","Lead",id,stage);return state}
export function saveCustomer(source,data){const state=clone(source);required(data,["name","type","mobile","stateCode"]);if(data.gstin&&!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/i.test(data.gstin))throw Error("Enter a valid GSTIN");const now=stamp(),old=state.customers.find(x=>x.id===data.id);const x={...old,...data,id:old?.id||nextNumber(state,"customer"),creditLimit:num(data.creditLimit),openingBalance:num(data.openingBalance),active:data.active!==false,createdAt:old?.createdAt||now,updatedAt:now};if(old)state.customers[state.customers.indexOf(old)]=x;else state.customers.unshift(x);log(state,old?"Updated":"Created","Customer",x.id);return{state,record:x}}
export function convertLeadToCustomer(source,id){let state=clone(source),lead=state.leads.find(x=>x.id===id);if(!lead)throw Error("Lead not found");if(lead.customerId)return{state,record:state.customers.find(x=>x.id===lead.customerId),duplicate:true};const result=saveCustomer(state,{type:"Business",name:lead.name,contactPerson:lead.contactPerson,mobile:lead.mobile,email:lead.email,stateCode:state.settings.sellerStateCode,placeOfSupply:state.settings.sellerStateCode,paymentTerms:30,active:true,notes:`Converted from ${lead.id}`});state=result.state;lead=state.leads.find(x=>x.id===id);lead.customerId=result.record.id;lead.updatedAt=stamp();log(state,"Converted","Lead",id,result.record.id);return{state,record:result.record,duplicate:false}}
export function saveActivity(source,data){const state=clone(source);required(data,["relatedId","type","dateTime","status"]);if(!ACTIVITY_TYPES.includes(data.type))throw Error("Invalid activity type");const old=state.activities.find(x=>x.id===data.id),x={...old,...data,id:old?.id||uid("ACT"),createdAt:old?.createdAt||stamp(),updatedAt:stamp()};if(old)state.activities[state.activities.indexOf(old)]=x;else state.activities.unshift(x);log(state,old?"Updated":"Created","Activity",x.id);return{state,record:x}}
function customer(state,id){const x=state.customers.find(r=>r.id===id);if(!x)throw Error("Select a valid customer");return x}
function saveDocument(source,data,type){const state=clone(source),c=customer(state,data.customerId);required(data,["date","customerId"]);const totals=documentTotals(data.items,state.settings,data.placeOfSupply||c.placeOfSupply||c.stateCode,data.additionalCharges,data.roundOff),list=type==="quotation"?state.quotations:type==="order"?state.orders:state.invoices,old=list.find(x=>x.id===data.id),status=data.status||(type==="invoice"?"Unpaid":"Draft"),x={...old,...data,...totals,placeOfSupply:data.placeOfSupply||c.placeOfSupply||c.stateCode,id:old?.id||nextNumber(state,type,data.date),status,createdAt:old?.createdAt||stamp(),updatedAt:stamp()};if(type==="invoice"){x.amountPaid=num(old?.amountPaid);x.balanceDue=round(x.grandTotal-x.amountPaid);x.status=invoiceStatus(x,data.dueDate||x.dueDate)}if(old)list[list.indexOf(old)]=x;else list.unshift(x);log(state,old?"Updated":"Created",type,x.id);return{state,record:x}}
export const saveQuotation=(s,d)=>saveDocument(s,d,"quotation");
export const saveOrder=(s,d)=>saveDocument(s,d,"order");
export const saveInvoice=(s,d)=>saveDocument(s,d,"invoice");
export function convertQuotationToOrder(source,id){const q=source.quotations.find(x=>x.id===id);if(!q)throw Error("Quotation not found");if(q.orderId)return{state:clone(source),record:source.orders.find(x=>x.id===q.orderId),duplicate:true};let {state,record}=saveOrder(source,{customerId:q.customerId,quotationId:q.id,leadId:q.leadId,date:today(),expectedDeliveryDate:"",items:q.items,placeOfSupply:q.placeOfSupply,additionalCharges:q.additionalCharges,roundOff:q.roundOff,notes:q.notes,terms:q.terms,status:"Confirmed"});state.quotations.find(x=>x.id===id).orderId=record.id;state.quotations.find(x=>x.id===id).status="Accepted";return{state,record,duplicate:false}}
export function convertOrderToInvoice(source,id){const o=source.orders.find(x=>x.id===id);if(!o)throw Error("Sales order not found");if(o.invoiceId)return{state:clone(source),record:source.invoices.find(x=>x.id===o.invoiceId),duplicate:true};const due=new Date();due.setDate(due.getDate()+num(source.customers.find(c=>c.id===o.customerId)?.paymentTerms||30));let {state,record}=saveInvoice(source,{customerId:o.customerId,orderId:o.id,quotationId:o.quotationId,date:today(),dueDate:due.toISOString().slice(0,10),items:o.items,placeOfSupply:o.placeOfSupply,additionalCharges:o.additionalCharges,roundOff:o.roundOff,notes:o.notes,terms:o.terms,status:"Unpaid"});state.orders.find(x=>x.id===id).invoiceId=record.id;state.orders.find(x=>x.id===id).status="Confirmed";return{state,record,duplicate:false}}
export function invoiceStatus(invoice,due=invoice.dueDate){if(invoice.status==="Cancelled")return"Cancelled";const balance=round(num(invoice.grandTotal)-num(invoice.amountPaid));if(balance<=0)return"Paid";if(num(invoice.amountPaid)>0)return"Partially Paid";return due&&due<today()?"Overdue":"Unpaid"}
export function recordPayment(source,data){const state=clone(source);required(data,["customerId","invoiceId","date","mode"]);const invoice=state.invoices.find(x=>x.id===data.invoiceId);if(!invoice||invoice.customerId!==data.customerId)throw Error("Select a valid customer invoice");const amount=num(data.amount);if(amount<=0)throw Error("Payment must be greater than zero");const outstanding=round(invoice.grandTotal-num(invoice.amountPaid));if(amount>outstanding)throw Error(`Payment exceeds outstanding ${money(outstanding)}`);const x={...data,amount,id:nextNumber(state,"payment",data.date),status:"Recorded",createdAt:stamp()};state.payments.unshift(x);invoice.amountPaid=round(num(invoice.amountPaid)+amount);invoice.balanceDue=round(invoice.grandTotal-invoice.amountPaid);invoice.status=invoiceStatus(invoice);log(state,"Recorded","Payment",x.id,invoice.id);return{state,record:x}}
export function reversePayment(source,id,reason){if(!reason.trim())throw Error("A reversal reason is required");const state=clone(source),x=state.payments.find(p=>p.id===id);if(!x||x.status==="Reversed")throw Error("Payment not found or already reversed");x.status="Reversed";x.reversalReason=reason;x.reversedAt=stamp();const invoice=state.invoices.find(i=>i.id===x.invoiceId);invoice.amountPaid=round(num(invoice.amountPaid)-x.amount);invoice.balanceDue=round(invoice.grandTotal-invoice.amountPaid);invoice.status=invoiceStatus(invoice);log(state,"Reversed","Payment",id,reason);return state}
export function createReturn(source,data){const state=clone(source),invoice=state.invoices.find(x=>x.id===data.invoiceId);if(!invoice)throw Error("Invoice not found");required(data,["date","reason"]);const prior=state.returns.filter(r=>r.invoiceId===invoice.id&&r.status!=="Cancelled"),items=data.items.filter(x=>num(x.quantity)>0).map(x=>{const sold=invoice.items.find(i=>String(i.productId||i.description)===String(x.productId||x.description));if(!sold)throw Error("Returned item is not on the invoice");const already=prior.flatMap(r=>r.items).filter(i=>String(i.productId||i.description)===String(x.productId||x.description)).reduce((a,i)=>a+num(i.quantity),0);if(num(x.quantity)>num(sold.quantity)-already)throw Error("Return quantity exceeds the remaining invoiced quantity");return{...sold,quantity:num(x.quantity)}});if(!items.length)throw Error("Select at least one returned item");const totals=documentTotals(items,state.settings,invoice.placeOfSupply,0,0),x={...data,...totals,id:nextNumber(state,"credit",data.date),customerId:invoice.customerId,status:"Issued",createdAt:stamp()};state.returns.unshift(x);log(state,"Issued","Credit Note",x.id,invoice.id);return{state,record:x}}
export function customerBalance(state,id){const c=state.customers.find(x=>x.id===id),invoices=state.invoices.filter(x=>x.customerId===id&&x.status!=="Cancelled"),credits=state.returns.filter(x=>x.customerId===id&&x.status!=="Cancelled");return round(num(c?.openingBalance)+invoices.reduce((a,x)=>a+num(x.grandTotal),0)-state.payments.filter(x=>x.customerId===id&&x.status!=="Reversed").reduce((a,x)=>a+num(x.amount),0)-credits.reduce((a,x)=>a+num(x.grandTotal),0))}
export function dashboardMetrics(state,now=new Date()){const day=now.toISOString().slice(0,10),month=day.slice(0,7),pending=a=>a.status==="Pending",active=state.leads.filter(x=>!x.archived);const invoices=state.invoices.filter(x=>x.status!=="Cancelled"),payments=state.payments.filter(x=>x.status!=="Reversed");return{totalLeads:active.length,todayFollowups:state.activities.filter(a=>pending(a)&&a.dateTime?.slice(0,10)===day).length,overdueFollowups:state.activities.filter(a=>pending(a)&&a.dateTime?.slice(0,10)<day).length,openOpportunities:active.filter(x=>!["Won","Lost"].includes(x.stage)).length,quotationsPending:state.quotations.filter(x=>["Draft","Sent"].includes(x.status)).length,confirmedOrders:state.orders.filter(x=>x.status==="Confirmed").length,unpaidInvoices:invoices.filter(x=>num(x.balanceDue)>0).length,monthSales:round(invoices.filter(x=>x.date?.startsWith(month)).reduce((a,x)=>a+num(x.grandTotal),0)),monthCollected:round(payments.filter(x=>x.date?.startsWith(month)).reduce((a,x)=>a+num(x.amount),0)),outstanding:round(state.customers.reduce((a,c)=>a+customerBalance(state,c.id),0))}}
export function reportRows(state,type){switch(type){case"Sales Summary":return state.invoices;case"Lead Conversion":return state.leads;case"Pipeline":return state.leads;case"Lead Source":return state.leads;case"Lost Lead Reasons":return state.leads.filter(x=>x.stage==="Lost");case"Salesperson Performance":return state.team;case"Customer-wise Sales":return state.customers.map(c=>({...c,totalSales:state.invoices.filter(i=>i.customerId===c.id).reduce((a,i)=>a+num(i.grandTotal),0),outstanding:customerBalance(state,c.id)}));case"Product-wise Sales":return state.invoices.flatMap(i=>i.items.map(x=>({...x,invoiceId:i.id,date:i.date})));case"Quotation Status":return state.quotations;case"Order Status":return state.orders;case"Invoice Register":case"Outstanding Receivables":case"GST Sales Summary":return type==="Outstanding Receivables"?state.invoices.filter(x=>num(x.balanceDue)>0):state.invoices;case"Payment Collection":return state.payments;case"Returns and Credit Notes":return state.returns;default:return[]}}
export function toCsv(rows){if(!rows.length)return"";const keys=[...new Set(rows.flatMap(Object.keys))].filter(k=>!Array.isArray(rows[0]?.[k])&&typeof rows[0]?.[k]!=="object");const cell=v=>`"${String(v??"").replaceAll('"','""')}"`;return[keys.map(cell).join(","),...rows.map(r=>keys.map(k=>cell(r[k])).join(","))].join("\r\n")}
