import { isPdfFile, hasPdfSignature, formatSize, classifyPdfLoadError, parseExtractPages, parseSplitRanges } from "./core.js";
const $ = (id) => document.getElementById(id); let selected = null, processing = false; const outputUrls = [];
function message(text = "", type = "error") { const el = $("spdf-message"); el.textContent = text; el.className = text ? `spdf-message ${type}` : "spdf-message"; }
function library() { return window.PDFLib?.PDFDocument ? window.PDFLib : null; }
function report(category, userMessage, error, details = {}) { console.error(`[Split PDF] ${category}`, { ...details, error }); message(userMessage); }
function clearOutputs() { outputUrls.splice(0).forEach((url) => URL.revokeObjectURL(url)); $("spdf-download-list").innerHTML = ""; $("spdf-downloads").style.display = "none"; }
function reset() { selected = null; $("spdf-file-input").value = ""; $("spdf-selected").style.display = "none"; $("spdf-pages-input").value = ""; clearOutputs(); message(); }

async function selectFile(file) {
  clearOutputs(); message(); if (!isPdfFile(file)) { console.warn("[Split PDF] Unsupported file type", { fileName: file?.name, fileType: file?.type }); message("Unsupported file type. Please choose a PDF file."); return; }
  const pdfLib = library(); if (!pdfLib) { report("PDF library load failure", "The PDF processing library did not load. Please refresh the page and try again.", new Error("window.PDFLib.PDFDocument is unavailable")); return; }
  try { const bytes = new Uint8Array(await file.arrayBuffer()); if (!hasPdfSignature(bytes)) throw Object.assign(new Error("Missing %PDF- file signature."), { code: "CORRUPTED" }); const document = await pdfLib.PDFDocument.load(bytes, { ignoreEncryption: false, updateMetadata: false }); selected = { file, bytes, pageCount: document.getPageCount() }; $("spdf-file-name").textContent = file.name; $("spdf-file-details").textContent = `${formatSize(file.size)} · ${selected.pageCount} page${selected.pageCount === 1 ? "" : "s"}`; $("spdf-selected").style.display = ""; }
  catch (error) { selected = null; $("spdf-selected").style.display = "none"; const kind = error.code || classifyPdfLoadError(error); if (kind === "ENCRYPTED") report("Encrypted PDF", `“${file.name}” is password-protected or encrypted and cannot be split in the browser.`, error, { fileName: file.name, fileSize: file.size }); else report("PDF decode failure", `“${file.name}” is corrupted or is not a readable PDF.`, error, { fileName: file.name, fileSize: file.size }); }
  finally { $("spdf-file-input").value = ""; }
}

function updateMethod() { const method = document.querySelector('input[name="spdf-method"]:checked').value; document.querySelectorAll(".spdf-method").forEach((el) => el.classList.toggle("active", el.querySelector("input").checked)); const field = $("spdf-range-field"); field.style.display = method === "every" ? "none" : ""; if (method === "extract") { $("spdf-pages-label").textContent = "Pages to extract"; $("spdf-pages-input").placeholder = "Example: 1-3,5,8-10"; $("spdf-pages-help").textContent = "Enter page numbers or ranges in the order they should appear."; } else if (method === "ranges") { $("spdf-pages-label").textContent = "Separate page ranges"; $("spdf-pages-input").placeholder = "Example: 1-3,4-7,8-10"; $("spdf-pages-help").textContent = "Each comma-separated range creates a separate PDF."; } clearOutputs(); message(); }

async function makeOutput(source, pages, filename, pdfLib) { const output = await pdfLib.PDFDocument.create(); const copied = await output.copyPages(source, pages.map((page) => page - 1)); copied.forEach((page) => output.addPage(page)); const bytes = await output.save({ useObjectStreams: true, addDefaultPage: false }); if (!bytes?.length) throw new Error(`An empty PDF was generated for ${filename}.`); return { filename, bytes, pageCount: pages.length }; }

async function splitPdf() {
  if (processing) return; if (!selected) { message("Please select a PDF file before splitting."); return; } const pdfLib = library(); if (!pdfLib) { report("PDF library load failure", "The PDF processing library did not load. Please refresh the page and try again.", new Error("window.PDFLib.PDFDocument is unavailable")); return; }
  const method = document.querySelector('input[name="spdf-method"]:checked').value; let specs;
  try { if (method === "extract") { const pages = parseExtractPages($("spdf-pages-input").value, selected.pageCount); specs = [{ pages, filename: "extracted-pages.pdf" }]; } else if (method === "ranges") specs = parseSplitRanges($("spdf-pages-input").value, selected.pageCount); else specs = Array.from({ length: selected.pageCount }, (_, index) => ({ pages: [index + 1], filename: `page-${index + 1}.pdf` })); }
  catch (error) { console.warn("[Split PDF] Invalid page selection", { input: $("spdf-pages-input").value, method, totalPages: selected.pageCount, error }); message(error.message); return; }
  processing = true; clearOutputs(); message(); $("spdf-split-btn").disabled = true; $("spdf-processing").style.display = "";
  try { const source = await pdfLib.PDFDocument.load(selected.bytes, { ignoreEncryption: false, updateMetadata: false }); const outputs = []; for (const spec of specs) { outputs.push(await makeOutput(source, spec.pages, spec.filename, pdfLib)); await new Promise((resolve) => setTimeout(resolve, 0)); } const list = $("spdf-download-list"); outputs.forEach((output) => { const blob = new Blob([output.bytes], { type: "application/pdf" }), url = URL.createObjectURL(blob); outputUrls.push(url); const row = document.createElement("div"); row.className = "spdf-download-row"; const label = document.createElement("span"); label.textContent = `${output.filename} · ${output.pageCount} page${output.pageCount === 1 ? "" : "s"}`; const link = document.createElement("a"); link.className = "btn btn-secondary btn-sm"; link.href = url; link.download = output.filename; link.textContent = outputs.length === 1 ? "Download PDF" : "Download"; row.append(label, link); list.appendChild(row); }); $("spdf-success-text").textContent = ` ${outputs.length} PDF${outputs.length === 1 ? " is" : "s are"} ready to download.`; $("spdf-downloads").style.display = ""; }
  catch (error) { const kind = classifyPdfLoadError(error); if (kind === "ENCRYPTED") report("Encrypted PDF", `“${selected.file.name}” is encrypted and cannot be split.`, error, { fileName: selected.file.name }); else report("PDF split failure", "The PDF was read, but the requested output files could not be generated. See the browser console for technical details.", error, { fileName: selected.file.name, method, outputCount: specs.length }); }
  finally { processing = false; $("spdf-split-btn").disabled = false; $("spdf-processing").style.display = "none"; }
}

const input = $("spdf-file-input"), dropzone = $("spdf-dropzone"); input.addEventListener("change", () => input.files[0] && selectFile(input.files[0])); $("spdf-remove-btn").addEventListener("click", reset); $("spdf-split-btn").addEventListener("click", splitPdf); document.querySelectorAll('input[name="spdf-method"]').forEach((radio) => radio.addEventListener("change", updateMethod)); dropzone.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); input.click(); } }); ["dragenter", "dragover"].forEach((name) => dropzone.addEventListener(name, (event) => { event.preventDefault(); dropzone.classList.add("spdf-dragover"); })); ["dragleave", "dragend"].forEach((name) => dropzone.addEventListener(name, () => dropzone.classList.remove("spdf-dragover"))); dropzone.addEventListener("drop", (event) => { event.preventDefault(); dropzone.classList.remove("spdf-dragover"); const files = [...event.dataTransfer.files]; if (files.length > 1) message("Please drop one PDF file at a time."); else if (files[0]) selectFile(files[0]); }); window.addEventListener("beforeunload", clearOutputs); updateMethod();
