export const ADMINISTRATION_KEY="infobridgeindia.administration.v2";
const CHANNEL_NAME="infobridgeindia-company-name";
export function selectedAdministrationCompany(state,companyId){const id=companyId||state?.currentCompanyId;return state?.companies?.find(company=>company.id===id)||state?.companies?.find(company=>company.id===state?.currentCompanyId)||null}
export function administrationCompanyName(company){return String(company?.tradeName||company?.legalName||"").trim()}
export function companyNameFromState(state,companyId){return administrationCompanyName(selectedAdministrationCompany(state,companyId))}
export function readAdministrationCompany(storage=globalThis.InfoBridgeWorkspaceStorage||globalThis.localStorage,companyId){try{const state=JSON.parse(storage?.getItem(ADMINISTRATION_KEY)||"null"),company=selectedAdministrationCompany(state,companyId||storage?.companyId||globalThis.InfoBridgeCompany?.companyId);return company?{...company,displayName:administrationCompanyName(company)}:null}catch{return null}}
export function currentAdministrationCompany(){return globalThis.InfoBridgeAdministrationCompany||readAdministrationCompany()}
export function currentCompanyName(fallback="Company"){return currentAdministrationCompany()?.displayName||fallback}
export function publishAdministrationCompany(state,companyId,{broadcast=true}={}){const company=selectedAdministrationCompany(state,companyId),displayName=administrationCompanyName(company);if(!company||!displayName)return null;const detail={...company,companyId:company.id,displayName};globalThis.InfoBridgeAdministrationCompany=detail;if(globalThis.InfoBridgeCompany?.companyId===company.id)globalThis.InfoBridgeCompany={...globalThis.InfoBridgeCompany,name:displayName,legalName:company.legalName,tradeName:company.tradeName};globalThis.dispatchEvent?.(new CustomEvent("infobridge:company-ready",{detail}));if(broadcast&&globalThis.BroadcastChannel){const channel=new BroadcastChannel(CHANNEL_NAME);channel.postMessage(detail);channel.close()}return detail}
export function listenForAdministrationCompany(callback){if(!globalThis.BroadcastChannel)return()=>{};const channel=new BroadcastChannel(CHANNEL_NAME);channel.onmessage=event=>{globalThis.InfoBridgeAdministrationCompany=event.data;if(globalThis.InfoBridgeCompany?.companyId===event.data?.companyId)globalThis.InfoBridgeCompany={...globalThis.InfoBridgeCompany,name:event.data.displayName};globalThis.dispatchEvent?.(new CustomEvent("infobridge:company-ready",{detail:event.data}));callback?.(event.data)};return()=>channel.close()}
