export const ADMINISTRATION_KEY="infobridgeindia.administration.v2";
const CHANNEL_NAME="infobridgeindia-company-name";
export function selectedAdministrationCompany(state,companyId){const id=companyId||state?.currentCompanyId;return state?.companies?.find(company=>company.id===id)||state?.companies?.find(company=>company.id===state?.currentCompanyId)||null}
export function administrationCompanyName(company){return String(company?.tradeName||company?.legalName||"").trim()}
export function companyNameFromState(state,companyId){return administrationCompanyName(selectedAdministrationCompany(state,companyId))}
export function readAdministrationCompany(storage=globalThis.InfoBridgeWorkspaceStorage||globalThis.localStorage,companyId){try{const state=JSON.parse(storage?.getItem(ADMINISTRATION_KEY)||"null"),company=selectedAdministrationCompany(state,companyId||storage?.companyId||globalThis.InfoBridgeCompany?.companyId);return company?{...company,displayName:administrationCompanyName(company)}:null}catch{return null}}
export function currentAdministrationCompany(){return globalThis.InfoBridgeAdministrationCompany||readAdministrationCompany()}
export function currentCompanyName(fallback="Company"){return currentAdministrationCompany()?.displayName||fallback}
export function publishAdministrationCompany(state,companyId,{broadcast=true}={}){const company=selectedAdministrationCompany(state,companyId),displayName=administrationCompanyName(company);if(!company||!displayName)return null;const detail={...company,companyId:company.id,displayName};globalThis.InfoBridgeAdministrationCompany=detail;if(globalThis.InfoBridgeCompany?.companyId===company.id)globalThis.InfoBridgeCompany={...globalThis.InfoBridgeCompany,name:displayName,legalName:company.legalName,tradeName:company.tradeName};globalThis.dispatchEvent?.(new CustomEvent("infobridge:company-ready",{detail}));if(broadcast&&globalThis.BroadcastChannel){const channel=new BroadcastChannel(CHANNEL_NAME);channel.postMessage(detail);channel.close()}return detail}
export function listenForAdministrationCompany(callback){if(!globalThis.BroadcastChannel)return()=>{};const channel=new BroadcastChannel(CHANNEL_NAME);channel.onmessage=async event=>{await globalThis.InfoBridgeRefreshAdministrationStorage?.();globalThis.InfoBridgeAdministrationCompany=event.data;if(globalThis.InfoBridgeCompany?.companyId===event.data?.companyId)globalThis.InfoBridgeCompany={...globalThis.InfoBridgeCompany,name:event.data.displayName};globalThis.dispatchEvent?.(new CustomEvent("infobridge:company-ready",{detail:event.data}));callback?.(event.data)};return()=>channel.close()}
export function reconcileAdministrationCompany(state,profile,countryConfig=globalThis.InfoBridgeCountryConfig){if(!state||!profile?.companyId)return state;const company=state.companies.find(x=>x.id===profile.companyId)||state.companies.find(x=>x.id===state.currentCompanyId)||state.companies[0];if(!company)return state;const oldId=company.id;Object.assign(company,{id:profile.companyId,legalName:profile.legalName||profile.name,tradeName:profile.name,businessType:profile.businessType,state:profile.state,country:countryConfig?.country||profile.country,currency:countryConfig?.currency||profile.currency,gstin:profile.gstin||"",gstStatus:profile.gstRegistered?"Registered":"Unregistered",trn:profile.trn||"",vatStatus:profile.vatRegistered?"Registered":"Unregistered",tradeLicenseNumber:profile.tradeLicenseNumber||"",tradeLicenseExpiryDate:profile.tradeLicenseExpiryDate||"",placeholder:false});for(const key of["branches","departments","companyMembers","roles","moduleAccess","financialYears","documentSequences","gstSettings","sharedMasters","notificationSettings","audit"])for(const row of state[key]||[])if(row.companyId===oldId)row.companyId=profile.companyId;state.currentCompanyId=profile.companyId;state.settings.defaultCompanyId=profile.companyId;state.settings.currencyFormat=countryConfig?.defaults?.locale||state.settings.currencyFormat;state.settings.timezone=countryConfig?.defaults?.timezone||state.settings.timezone;return state}
