import{resolveCountryConfig,supportedCountryOptions}from"../country/registry.js";
import{ADMIN_TAX_TYPES,administrationCompanyFormModel}from"./company-form.js";
import{saveBranch,uid}from"./core.js";

export function branchTaxTypes(country){const system=resolveCountryConfig(country).tax.system;return ADMIN_TAX_TYPES.filter(type=>type===system||type==="No Tax")}
const rawRegion=value=>String(value||"").trim();
const inferredTaxType=seed=>ADMIN_TAX_TYPES.includes(seed.taxType)?seed.taxType:ADMIN_TAX_TYPES.includes(seed.taxSystem)?seed.taxSystem:seed.trn?"VAT":seed.gstin?"GST":"No Tax";

export function administrationBranchFormModel(branch={},company={}){const existing=branch.id||branch.code||branch.name||branch.gstin||branch.trn||branch.state||branch.emirate,seed=existing&&!branch.placeholder?branch:{...company,...branch},config=resolveCountryConfig(seed.country||company.country),taxTypes=branchTaxTypes(config.country),candidateRegion=rawRegion(seed.region||seed.emirate||seed.state),candidateTaxType=inferredTaxType(seed),region=config.jurisdictions.includes(candidateRegion)?candidateRegion:"",taxType=taxTypes.includes(candidateTaxType)?candidateTaxType:"No Tax",taxNumber=taxType==="No Tax"?"":seed.taxNumber||(taxType==="VAT"?seed.trn:seed.gstin)||"";return{country:config.country,countries:supportedCountryOptions(),regions:config.jurisdictions,region,taxTypes,taxType,taxNumber,postalCode:seed.postalCode||seed.pinCode||"",address:seed.address||seed.businessAddress||seed.registeredAddress||""}}

export function normalizeAdministrationBranchInput(data,company){const config=resolveCountryConfig(data.country||company.country),allowedTaxTypes=branchTaxTypes(config.country),taxType=ADMIN_TAX_TYPES.includes(data.taxType)?data.taxType:"No Tax",taxNumber=taxType==="No Tax"?"":String(data.taxNumber||"").trim().toUpperCase(),region=rawRegion(data.region);if(!config.jurisdictions.includes(region))throw Error(`Select a valid Region for ${config.countryName}`);if(!allowedTaxTypes.includes(taxType))throw Error(`${taxType} is not a valid Tax Type for ${config.countryName}`);if(taxType===config.tax.system&&(!taxNumber||!config.tax.validateIdentifier(taxNumber)))throw Error(config.country==="IN"?"Enter a valid GSTIN":"Enter a valid 15-digit TRN");return{...data,companyId:company.id,country:config.country,state:region,region,emirate:config.country==="AE"?region:"",taxType,taxSystem:taxType,taxNumber,gstin:taxType==="GST"?taxNumber:"",trn:taxType==="VAT"?taxNumber:"",postalCode:data.postalCode||"",pinCode:data.postalCode||"",isDefault:data.isDefault===true||data.isDefault==="true"}}

export function saveConfiguredBranch(source,data,company){const old=data.id&&source.branches.find(x=>x.id===data.id);if(old&&old.companyId!==company.id)throw Error("This branch belongs to another company");return saveBranch(source,normalizeAdministrationBranchInput(data,company))}

function isLegacyHeadOffice(head,company){if(!head)return true;if(head.placeholder)return true;const config=resolveCountryConfig(head.country||company.country),candidateRegion=rawRegion(head.region||head.emirate||head.state),candidateTax=inferredTaxType(head);return Boolean(head.isDefault&&(head.code==="HO"||head.name==="Head Office")&&(!config.jurisdictions.includes(candidateRegion)||!branchTaxTypes(config.country).includes(candidateTax)))}

export function reconcileCompanyHeadOffice(state,company){if(!state||!company?.id)return state;let head=state.branches.find(x=>x.companyId===company.id&&(x.code==="HO"||x.name==="Head Office"));if(head&&!isLegacyHeadOffice(head,company))return state;const companyModel=administrationCompanyFormModel(company),model=administrationBranchFormModel({...company,country:companyModel.country,region:companyModel.region,taxType:companyModel.taxType,taxNumber:companyModel.taxNumber},company),values={name:"Head Office",code:"HO",companyId:company.id,country:model.country,state:model.region,region:model.region,emirate:model.country==="AE"?model.region:"",address:company.businessAddress||company.registeredAddress||model.address,city:company.city||model.region,postalCode:company.postalCode||company.pinCode||model.postalCode,email:company.email||"",mobile:company.mobile||"",taxType:model.taxType,taxSystem:model.taxType,taxNumber:model.taxNumber,gstin:model.taxType==="GST"?model.taxNumber:"",trn:model.taxType==="VAT"?model.taxNumber:"",active:true,isDefault:true,placeholder:false};if(head)Object.assign(head,values);else{head={id:uid("BR"),...values,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.branches.push(head)}for(const branch of state.branches)if(branch.companyId===company.id&&branch!==head&&branch.isDefault)branch.isDefault=false;state.currentBranchId=head.id;state.settings.defaultBranchId=head.id;return state}

export function orderedCompanyBranches(branches,companyId){return branches.filter(x=>x.companyId===companyId).sort((a,b)=>Number(!(a.code==="HO"||a.name==="Head Office"))-Number(!(b.code==="HO"||b.name==="Head Office"))||String(a.createdAt||"").localeCompare(String(b.createdAt||""))||String(a.id).localeCompare(String(b.id)))}
