import{FIELDS,checklist,validateRow,classify,summaries,gstinValid}from"./core.js";
import{detectMapping,isMeeshoReport,normalizeMeeshoRows,validateTransactions,importStatus,filingReadiness,consolidate,gstr1Json}from"./ecommerce-core.js";
import{XLSX}from"./xlsx-shim.js";
import{processMeesho}from"./marketplace-meesho.js";
import{processFlipkart}from"./marketplace-flipkart.js";
import{processCombined}from"./marketplace-combined.js";
import{createPublicGstStore}from"./public-store.js";
const DB="InfoBridgeIndiaGST",STORES=["setup","uploads","mappings","rows","settings"];let store,state={},view="gstr1",pending=null;
const $=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),uid=p=>`${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(+n||0);
async function openDb(){store=createPublicGstStore()}const all=s=>store.all(s),put=(s,v)=>store.put(s,v);async function load(){for(const s of STORES)state[s]=await all(s)}
async function clearActiveWorkspace(){for(const collection of STORES)await store.clear(collection)}
function toast(t,e=false){const x=document.createElement("div");x.className=`toast${e?" error":""}`;x.textContent=t;$("#gst-toast").append(x);setTimeout(()=>x.remove(),3500)}const btn=(t,a,c="secondary")=>`<button class="btn ${c}" ${a}>${t}</button>`;
function setupPage(){return`<main class="gst-setup"><section class="setup-card"><a href="/index.html"><img class="brand-logo" src="/infobridgeindia-logo.png"></a><h1>Set up GST & Compliance</h1><p class="muted">Answer only what applies to your business. Required-data decisions use explicit rules, not AI guesses.</p><form id="setup-form"><div class="form-grid"><label>GSTIN<input class="input" name="gstin" id="gstin" required maxlength="15"></label><label>Legal / Business Name<input class="input" name="legalName" required></label><label>State<input class="input" name="state" required></label><label>Taxpayer Type<select class="input" name="taxpayerType"><option>Regular</option><option>Composition</option></select></label><label>Return Frequency<select class="input" name="frequency"><option>Monthly</option><option>Quarterly / QRMP</option></select></label><label>Business Type<select class="input" name="businessType" id="business-type"><option>Retail</option><option selected>Wholesale</option><option>Distributor</option><option>Service Business</option><option>E-commerce Seller</option><option>E-commerce</option><option>Manufacturer</option><option>Import / Export</option><option>Other / Custom</option></select></label><div class="full" id="conditional"></div></div><div class="actions" style="justify-content:flex-end;margin-top:20px">${btn("Complete GST Setup","","primary")}</div></form></section></main>`}
function conditional(type){return type==="E-commerce Seller"?`<div class="panel padded"><strong>Sales channel</strong><div class="actions" style="margin-top:10px"><label><input type="checkbox" name="marketplaces" value="Meesho" checked> Meesho</label></div><label class="setup-period">Filing period<input class="input" type="month" name="filingPeriod" required></label><label><input type="checkbox" name="section9_5"> This business has explicitly identified section 9(5) supplies</label></div>`:type==="Wholesale"?`<div class="panel padded"><strong>Wholesale activity</strong><div class="actions" style="margin-top:10px"><label><input type="checkbox" name="hasB2c"> B2C sales</label><label><input type="checkbox" name="hasNotes"> Credit/debit notes</label><label><input type="checkbox" name="hasExports"> Export / SEZ sales</label></div></div>`:type==="E-commerce"?ecommercePanelHtml():""}

/* -----------------------------------------------------------------------
   E-commerce (Meesho / Flipkart) GSTR-1 panel.
   Reuses the existing working Meesho / Flipkart / Combined GSTR-1 logic
   migrated from the old InfoBridgeIndia website (see
   reference-files/Infobridgeindia-old-website.zip -> js/meesho.js,
   js/flipkart.js, js/combined-gstr1.js) via ./marketplace-meesho.js,
   ./marketplace-flipkart.js and ./marketplace-combined.js. Those modules
   carry the calculations unmodified; only Excel I/O (./xlsx-shim.js
   instead of the old CDN-loaded SheetJS) and this UI wiring are new.
   ----------------------------------------------------------------------- */

const ECOM_UPLOAD_LABELS={meeshoSales:"Meesho Sales Report",meeshoReturn:"Meesho Return Report",flipkartSales:"Flipkart Sales Report"};

function ecommercePanelHtml(){return`<div class="panel padded" id="ecommerce-panel"><strong>Marketplace Activity</strong><div class="actions" style="margin-top:10px"><label><input type="checkbox" id="mkt-meesho" name="ecomMarketplaces" value="Meesho"> Meesho</label><label><input type="checkbox" id="mkt-flipkart" name="ecomMarketplaces" value="Flipkart"> Flipkart</label></div><label class="setup-period">Filing period<input class="input" type="month" id="ecomFilingPeriod" required></label><div id="ecom-uploads" style="margin-top:12px">${ecomUploadsPlaceholder()}</div><p id="ecom-status" class="readiness" style="display:none"><strong id="ecom-status-title"></strong><span id="ecom-status-detail"></span></p><div class="actions" style="margin-top:14px"><button type="button" class="btn primary" id="ecom-generate-btn" disabled>Generate GST Report</button></div><div id="ecom-downloads" class="actions" style="display:none;margin-top:12px"><button type="button" class="btn secondary" id="ecom-download-excel">Download Excel</button><button type="button" class="btn secondary" id="ecom-download-json">Download GST JSON</button></div></div>`}

function ecomUploadsPlaceholder(){return`<p class="muted">Select Meesho and/or Flipkart above to continue.</p>`}

function ecomUploadsHtml(keys){return`<div class="upload-grid grid" style="grid-template-columns:1fr 1fr">${keys.map(k=>`<article class="upload-card"><h3>${ECOM_UPLOAD_LABELS[k]}</h3><label class="btn secondary file-btn">Choose file<input type="file" accept=".xlsx" data-ecom-file="${k}"></label><span class="muted" data-ecom-file-name="${k}" style="display:block;margin-top:6px;font-size:11px">No file selected · .xlsx only</span></article>`).join("")}</div>`}

function ecomNeededKeys(selected){const keys=[];if(selected.includes("Meesho"))keys.push("meeshoSales","meeshoReturn");if(selected.includes("Flipkart"))keys.push("flipkartSales");return keys}

function toFilingPeriodLocal(monthValue){const text=String(monthValue||"").trim();const m=text.match(/^(\d{4})-(\d{2})$/);if(!m)return null;const year=m[1],month=m[2];const label=new Date(Number(year),Number(month)-1,1).toLocaleString("en-US",{month:"long",year:"numeric"});return{fp:`${month}${year}`,label}}

function bindMarketplacePanel(){
  const panel=$("#ecommerce-panel");if(!panel)return;
  const uploadsBox=$("#ecom-uploads"),generateBtn=$("#ecom-generate-btn"),statusBox=$("#ecom-status"),statusTitle=$("#ecom-status-title"),statusDetail=$("#ecom-status-detail"),downloadsBox=$("#ecom-downloads");
  const files={};let currentKeys=[],lastResult=null;

  function selectedMarketplaces(){return[...panel.querySelectorAll('input[name="ecomMarketplaces"]:checked')].map(cb=>cb.value)}

  function setStatus(kind,title,detail){statusBox.style.display="";statusBox.className=`readiness ${kind}`;statusTitle.textContent=title;statusDetail.textContent=detail||""}
  function clearStatus(){statusBox.style.display="none";downloadsBox.style.display="none";lastResult=null}

  function updateGenerateEnabled(){const selected=selectedMarketplaces();let ready=false;if(selected.includes("Meesho")&&selected.includes("Flipkart"))ready=Boolean(files.meeshoSales&&files.meeshoReturn&&files.flipkartSales);else if(selected.includes("Meesho"))ready=Boolean(files.meeshoSales&&files.meeshoReturn);else if(selected.includes("Flipkart"))ready=Boolean(files.flipkartSales);generateBtn.disabled=!ready}

  const ECOM_MAX_FILE_SIZE=25*1024*1024;// 25 MB - generous for a marketplace report, guards against an accidental huge/wrong file hanging the tab
  function wireUploadInputs(){uploadsBox.querySelectorAll("[data-ecom-file]").forEach(input=>{input.addEventListener("change",()=>{const key=input.dataset.ecomFile,picked=input.files[0]||null;const nameEl=uploadsBox.querySelector(`[data-ecom-file-name="${key}"]`);if(picked&&picked.size>ECOM_MAX_FILE_SIZE){files[key]=null;input.value="";if(nameEl)nameEl.textContent="No file selected · .xlsx only";setStatus("not-ready","File too large",`${ECOM_UPLOAD_LABELS[key]} is ${(picked.size/(1024*1024)).toFixed(1)} MB, which is over the 25 MB limit.`);updateGenerateEnabled();return}files[key]=picked;if(nameEl)nameEl.textContent=files[key]?files[key].name:"No file selected · .xlsx only";clearStatus();updateGenerateEnabled()})})}

  function refreshUploads(){
    const selected=selectedMarketplaces(),needed=ecomNeededKeys(selected);
    const sameSet=needed.length===currentKeys.length&&needed.every(k=>currentKeys.includes(k));
    if(!sameSet){
      uploadsBox.innerHTML=needed.length?ecomUploadsHtml(needed):ecomUploadsPlaceholder();
      Object.keys(files).forEach(k=>{if(!needed.includes(k))delete files[k]});
      currentKeys=needed;
      wireUploadInputs();
      // A native <input type=file> can't have its selected-file display
      // restored programmatically, but the filename label can be re-synced
      // from the still-held File object so an already-selected file for a
      // marketplace that remains checked doesn't misleadingly show empty.
      needed.forEach(k=>{if(files[k]){const nameEl=uploadsBox.querySelector(`[data-ecom-file-name="${k}"]`);if(nameEl)nameEl.textContent=files[k].name}});
    }
    clearStatus();
    updateGenerateEnabled();
  }

  panel.querySelectorAll('input[name="ecomMarketplaces"]').forEach(cb=>cb.addEventListener("change",refreshUploads));
  $("#ecomFilingPeriod").addEventListener("change",clearStatus);

  generateBtn.addEventListener("click",async()=>{
    clearStatus();
    const gstinField=$("#gstin");
    const gstin=String(gstinField?.value||"").trim().toUpperCase().replace(/\s+/g,"");
    if(!gstinValid(gstin)){setStatus("not-ready","GSTIN required","Enter a valid 15-character GSTIN in the field above before generating.");return}
    const period=toFilingPeriodLocal($("#ecomFilingPeriod").value);
    if(!period){setStatus("not-ready","Filing period required","Select the filing period (month and year) above.");return}
    const selected=selectedMarketplaces();
    if(!selected.length){setStatus("not-ready","Select a marketplace","Check Meesho and/or Flipkart above first.");return}

    generateBtn.disabled=true;
    setStatus("review","Generating GST report…","This can take a moment for larger reports.");

    try{
      let result;
      if(selected.includes("Meesho")&&selected.includes("Flipkart")){
        result=await processCombined({meeshoSalesFile:files.meeshoSales,meeshoReturnFile:files.meeshoReturn,flipkartSalesFile:files.flipkartSales,gstin,fp:period.fp});
      }else if(selected.includes("Meesho")){
        result=await processMeesho({salesFile:files.meeshoSales,returnFile:files.meeshoReturn,gstin,fp:period.fp});
      }else{
        result=await processFlipkart({salesFile:files.flipkartSales,gstin,fp:period.fp});
      }
      lastResult=result;
      setStatus("ready","GST report ready",`Net Taxable ${money(result.summary.netTaxable)} · IGST ${money(result.summary.netIGST)} · CGST ${money(result.summary.netCGST)} · SGST ${money(result.summary.netSGST)}`);
      downloadsBox.style.display="";
    }catch(err){
      setStatus("not-ready","Could not generate the GST report",err.message||"Please check the uploaded files and try again.");
    }finally{
      generateBtn.disabled=false;
      updateGenerateEnabled();
    }
  });

  $("#ecom-download-excel").addEventListener("click",()=>{if(!lastResult)return;XLSX.writeFile(lastResult.workbook,lastResult.workbookFileName)});
  $("#ecom-download-json").addEventListener("click",()=>{if(!lastResult)return;dl(lastResult.jsonFileName,JSON.stringify(lastResult.jsonData))});

  refreshUploads();
}
function shell(content){const nav=[["setup","GST Setup"],["gstr1","GSTR-1"],["gstr3b","GSTR-3B"],["gstr2b","GSTR-2B Reconciliation"],["hsn","HSN / SAC"],["ecommerce","E-commerce GST"],["reports","Reports"],["backup","Backup / Restore"]];return`<div class="gst-shell"><aside class="gst-sidebar"><a class="gst-brand" href="/index.html"><img src="/infobridgeindia-logo.png"></a><div class="gst-label"><strong>GST & Compliance</strong><span>${esc(state.setup[0].gstin)}</span></div><nav>${nav.map(([v,t])=>`<button class="gst-nav ${view===v?"active":""}" data-view="${v}">${t}</button>`).join("")}</nav><div class="local-note">GST preparation data stays in this browser.<br>Maintain regular backups.<button type="button" class="change-business" data-change-business>Change Business</button></div></aside><main class="gst-main"><header class="gst-top"><strong>GST & Compliance</strong><span class="badge info">Preparation only · No direct filing</span></header><div class="gst-content">${content}</div></main></div>`}
const head=(t,d,a="")=>`<div class="page-head"><div><h1>${t}</h1><p>${d}</p></div><div class="actions">${a}</div></div>`;
function workspaceSummaries(rows){if(state.setup[0].businessType!=="E-commerce Seller")return summaries(rows);const ec=consolidate(rows);return{groups:{B2B:ec.b2b,B2C:ec.b2c,"Credit / Debit Notes":ec.notes,Exports:[],"E-commerce":ec.eco},hsn:ec.hsn.map(x=>({audience:"All",...x,taxableValue:x.txval,quantity:x.qty,gstRate:x.rate,igst:x.iamt,cgst:x.camt,sgst:x.samt,cess:x.csamt})),documents:ec.documents.map(x=>({category:x.category,issued:x.total,from:x.from,to:x.to}))}}
function dashboard(){const rows=state.rows,stats=countStats(rows),ecom=state.setup[0].businessType==="E-commerce Seller",sum=workspaceSummaries(rows),ready=ecom?filingReadiness(rows,state.setup[0]):null;return head("GSTR-1 preparation","Upload, map, validate, classify and review outward supplies.",btn("Download GSTR-1 Excel Report","data-xlsx")+btn("Download GSTR-1 JSON",`data-json ${ready&&!ready.ready?"disabled title=\"Resolve critical issues and review rows first\"":""}`,ready?.ready?"primary":"secondary"))+`${ready?`<div class="readiness ${ready.ready?"ready":ready.state==="Needs Review"?"review":"not-ready"}"><strong>${ready.state}</strong><span>${[...ready.missing,ready.critical?`${ready.critical} critical row(s)`:"",ready.review?`${ready.review} row(s) need confirmation`:""].filter(Boolean).join(" · ")||"All critical checks passed"}</span></div>`:""}<div class="metrics"><div class="metric"><span>Uploaded rows</span><strong>${rows.filter(r=>!r.duplicate).length}</strong></div><div class="metric"><span>Valid</span><strong>${stats.valid}</strong></div><div class="metric"><span>Warnings / Review</span><strong>${stats.warnings+stats.review}</strong></div><div class="metric"><span>Errors</span><strong>${stats.errors}</strong></div></div>${checklistPanel()}${uploadPanel()}${reviewPanel(sum,stats)}`}
const countStats=rows=>({valid:rows.filter(r=>r.validation?.severity==="Valid"&&!r.duplicate).length,warnings:rows.filter(r=>r.validation?.severity==="Warning"&&!r.duplicate).length,review:rows.filter(r=>r.validation?.severity==="Needs Review"&&!r.duplicate).length,errors:rows.filter(r=>r.validation?.severity==="Error"&&!r.excluded&&!r.duplicate).length,excluded:rows.filter(r=>r.excluded).length,duplicates:rows.filter(r=>r.duplicate).length});
function checklistPanel(){const uploaded=new Set(state.uploads.map(x=>x.reportKey));return`<section class="panel"><div class="panel-head"><h2>Required data checklist</h2></div><div class="panel padded checklist">${checklist(state.setup[0]).map(x=>`<div class="check-row"><div><strong>${esc(x.label)}</strong><div class="muted">${x.required?"Required":x.derived?"Derived where possible":"Optional"}</div></div><span class="badge ${uploaded.has(x.key)?"success":x.required?"warning":"neutral"}">${uploaded.has(x.key)?"Uploaded":x.derived?"Derived / Needs Review":x.required?"Missing":"Optional"}</span></div>`).join("")}</div></section>`}
function uploadPanel(){if(state.setup[0].businessType==="E-commerce Seller")return`<section class="panel marketplace-upload"><div class="panel-head"><h2>Upload Marketplace GST Report</h2></div><div class="panel padded"><p>Upload the complete GST report/package downloaded from your marketplace. ZIP, Excel, CSV and JSON are supported.</p><label class="btn secondary file-btn">Add Marketplace Report<input type="file" data-marketplace-upload multiple accept=".csv,.json,.xlsx,.zip"></label>${state.uploads.length?`<div class="detected-list"><h3>What InfoBridgeIndia detected</h3>${state.uploads.map(u=>`<article><strong>${esc(u.marketplace||"Marketplace needs confirmation")}</strong><span>${esc(u.fileName)} · ${u.filesDetected||1} file(s) · ${esc(u.reportTypes||"Unknown")} · ${u.rowCount} rows</span><span class="badge ${u.status==="Ready"?"success":"warning"}">${esc(u.status)}</span></article>`).join("")}</div>`:""}</div></section>`;return`<section class="panel"><div class="panel-head"><h2>Upload structured reports</h2></div><div class="panel padded"><div class="upload-grid grid">${checklist(state.setup[0]).filter(x=>x.key!=="documents").map(x=>`<article class="upload-card"><h3>${esc(x.label)}</h3><p>CSV and JSON are imported directly. XLSX and ZIP are inspected when supported; legacy XLS is reported as unsupported.</p><label class="btn secondary file-btn">Choose file<input type="file" data-upload="${esc(x.key)}" accept=".csv,.json,.xlsx,.xls,.zip"></label></article>`).join("")}</div></div></section>`}
function reviewPanel(sum,stats){const groupRows=Object.entries(sum.groups).map(([k,v])=>`<tr><td><strong>${k}</strong></td><td>${v.length}</td><td>${money(v.reduce((s,r)=>s+(+r.taxableValue||0),0))}</td><td>${money(v.reduce((s,r)=>s+(+r.igst||0)+(+r.cgst||0)+(+r.sgst||0)+(+r.cess||0),0))}</td></tr>`).join("");return`<section class="panel"><div class="panel-head"><h2>Review & classification</h2><span>${stats.excluded} excluded</span></div><div class="panel padded"><div class="tabs"><button class="tab active" data-review="summary">Summary</button><button class="tab" data-review="rows">Rows & validation</button><button class="tab" data-review="hsn">HSN Summary</button><button class="tab" data-review="documents">Document Summary</button></div><div id="review-body"><div class="table-wrap"><table><thead><tr><th>GSTR-1 group</th><th>Rows</th><th>Taxable value</th><th>Tax total</th></tr></thead><tbody>${groupRows}</tbody></table></div></div></div></section>`}
function rowsReview(){return`<div class="table-wrap"><table><thead><tr><th>Source</th><th>Invoice / Order</th><th>Date</th><th>GSTIN</th><th>Classification</th><th>Taxable</th><th>Validation</th><th>Actions</th></tr></thead><tbody>${state.rows.map(r=>`<tr><td><strong>${esc(r.marketplace||r.source||"Needs confirmation")}</strong><div>${esc(r.sourceFile||"")} · ${esc(r.sourceSheet||"")} · row ${r.sourceRow||"—"}</div></td><td>${esc(r.invoiceNumber||r.orderId)}</td><td>${esc(r.invoiceDate)}</td><td>${esc(r.buyerGstin)}</td><td>${classify(r)}</td><td>${money(r.taxableValue)}</td><td><span class="badge ${r.excluded||r.duplicate?"neutral":r.validation.severity==="Error"?"danger":r.validation.severity==="Valid"?"success":"warning"}">${r.excluded?"Excluded":r.duplicate?"Duplicate":r.validation.severity}</span><div>${esc([...(r.validation.errors||[]),...(r.validation.review||[]),...(r.validation.warnings||[])].join("; "))}</div></td><td>${btn("Correct",`data-correct="${r.id}"`)} ${btn(r.excluded?"Include":"Exclude",`data-exclude="${r.id}"`)}</td></tr>`).join("")}</tbody></table></div>`}
function hsnReview(sum){return`<div class="table-wrap"><table><thead><tr><th>Supply</th><th>HSN/SAC</th><th>UQC</th><th>Quantity</th><th>Rate</th><th>Taxable</th><th>IGST</th><th>CGST</th><th>SGST</th></tr></thead><tbody>${sum.hsn.map(x=>`<tr><td>${x.audience}</td><td>${esc(x.hsn)}</td><td>${esc(x.uqc)}</td><td>${x.quantity}</td><td>${x.gstRate}%</td><td>${money(x.taxableValue)}</td><td>${money(x.igst)}</td><td>${money(x.cgst)}</td><td>${money(x.sgst)}</td></tr>`).join("")}</tbody></table></div>`}
function docReview(sum){return`<div class="table-wrap"><table><thead><tr><th>Category</th><th>Issued</th><th>From</th><th>To</th></tr></thead><tbody>${sum.documents.map(x=>`<tr><td>${esc(x.category)}</td><td>${x.issued}</td><td>${esc(x.from)}</td><td>${esc(x.to)}</td></tr>`).join("")}</tbody></table>${sum.documents.length?"":'<div class="placeholder">Additional document details required</div>'}</div>`}
function placeholder(){return head(view==="setup"?"GST Setup":view.replace("gstr","GSTR-"),"This section is navigation-ready. GSTR-1 is the working feature in this phase.",view==="setup"?btn("Edit setup","data-edit-setup","primary"):"")+`<section class="panel placeholder"><h2>Coming in a later GST phase</h2><p class="muted">No filing or reconciliation claim is made for this section yet.</p></section>`}
function backupPage(){return head("Backup / Restore","Continue GST preparation safely on this browser.")+`<section class="panel padded"><h2>Full workspace backup</h2><p class="muted">Includes GST setup, uploaded/imported structured data, mappings, corrections, validation and classifications.</p><div class="actions">${btn("Download Full GST Workspace Backup (.json)","data-backup","primary")}<label class="btn secondary file-btn">Restore Previous GST Workspace Backup (.json)<input id="restore" type="file" accept=".json"></label></div></section><p class="privacy">GST preparation data is stored locally in the browser for this version. Maintain backups. No cloud storage or encryption is claimed.</p>`}
function render(){if(!state.setup?.length){$("#gst-app").innerHTML=setupPage();bindSetup();return}$("#gst-app").innerHTML=shell(view==="gstr1"?dashboard():view==="backup"?backupPage():placeholder());bind()}
function bindSetup(){const t=$("#business-type"),box=$("#conditional");const renderConditional=()=>{box.innerHTML=conditional(t.value);if(t.value==="E-commerce")bindMarketplacePanel()};renderConditional();t.onchange=renderConditional;$("#setup-form").onsubmit=async e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f));v.marketplaces=new FormData(f).getAll("marketplaces");for(const k of["hasB2c","hasNotes","hasExports","ownWebsite","offlineSales","section9_5"])v[k]=f.elements[k]?.checked||false;if(v.businessType==="E-commerce Seller")v.schemaVerified=true;if(!gstinValid(v.gstin))return toast("Enter a valid 15-character GSTIN",true);await put("setup",{...v,id:"gst-setup",createdAt:new Date().toISOString()});await load();render()}}
function bind(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll("[data-upload]").forEach(i=>i.onchange=e=>uploadFile(e.target.files[0],i.dataset.upload));$("[data-marketplace-upload]")?.addEventListener("change",e=>uploadMarketplaceFiles([...e.target.files]));document.querySelectorAll("[data-review]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-review]").forEach(x=>x.classList.toggle("active",x===b));const sum=workspaceSummaries(state.rows);$("#review-body").innerHTML=b.dataset.review==="rows"?rowsReview():b.dataset.review==="hsn"?hsnReview(sum):b.dataset.review==="documents"?docReview(sum):reviewPanel(sum,countStats(state.rows));bindRowActions()});bindRowActions();$("[data-json]")?.addEventListener("click",exportJson);$("[data-xlsx]")?.addEventListener("click",exportReview);$("[data-backup]")?.addEventListener("click",backup);$("#restore")?.addEventListener("change",restore);$("[data-change-business]")?.addEventListener("click",changeBusinessDialog);$("[data-edit-setup]")?.addEventListener("click",()=>toast("Setup editing will be added without changing saved transaction data."))}
function bindRowActions(){document.querySelectorAll("[data-exclude]").forEach(b=>b.onclick=async()=>{const r=state.rows.find(x=>x.id===b.dataset.exclude);await put("rows",{...r,excluded:!r.excluded});await load();render()});document.querySelectorAll("[data-correct]").forEach(b=>b.onclick=()=>correct(b.dataset.correct))}
function parseCsv(text){const first=(text.split(/\r?\n/).find(Boolean)||""),delimiter=[[",",(first.match(/,/g)||[]).length],["\t",(first.match(/\t/g)||[]).length],[";",(first.match(/;/g)||[]).length],["|",(first.match(/\|/g)||[]).length]].sort((a,b)=>b[1]-a[1])[0][0],rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===delimiter&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>String(x).trim()))rows.push(row);return matrixToRows(rows)}
function matrixToRows(matrix){let best={index:0,score:-1};for(let i=0;i<Math.min(matrix.length,20);i++){const headers=matrix[i].map(x=>String(x??"").trim()),score=Object.keys(detectMapping(headers).mapping).length;if(score>best.score)best={index:i,score}}const headers=(matrix[best.index]||[]).map(x=>String(x??"").trim());return matrix.slice(best.index+1).filter(r=>r.some(x=>String(x??"").trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h||`Column ${i+1}`,String(r[i]??"").trim()]))) }
async function fingerprint(file){const hash=await crypto.subtle.digest("SHA-256",await file.arrayBuffer());return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function jsonArrays(value,path="JSON",out=[]){if(Array.isArray(value)){if(value.length&&value.every(x=>x&&typeof x==="object"&&!Array.isArray(x)))out.push({sheetName:path,rows:value});else value.forEach((x,i)=>jsonArrays(x,`${path}[${i}]`,out))}else if(value&&typeof value==="object")for(const[k,v]of Object.entries(value))jsonArrays(v,`${path}.${k}`,out);return out}
async function workbookDatasets(blob,fileName){const files=await unzip(blob),parser=new DOMParser(),sharedFile=files["xl/sharedStrings.xml"],shared=sharedFile?[...parser.parseFromString(sharedFile.text(),"application/xml").querySelectorAll("si")].map(x=>x.textContent):[],workbook=files["xl/workbook.xml"],rels=files["xl/_rels/workbook.xml.rels"];if(!workbook)throw Error("Workbook structure is missing");const relMap={};if(rels)for(const r of parser.parseFromString(rels.text(),"application/xml").querySelectorAll("Relationship"))relMap[r.getAttribute("Id")]=r.getAttribute("Target");const sheets=[...parser.parseFromString(workbook.text(),"application/xml").querySelectorAll("sheet")],out=[];for(let si=0;si<sheets.length;si++){const s=sheets[si],rid=s.getAttribute("r:id")||s.getAttributeNS("http://schemas.openxmlformats.org/officeDocument/2006/relationships","id"),target=relMap[rid],path=target?`xl/${target.replace(/^\/?xl\//,"")}`:`xl/worksheets/sheet${si+1}.xml`,item=files[path];if(!item)continue;const xml=parser.parseFromString(item.text(),"application/xml"),matrix=[];for(const row of xml.querySelectorAll("sheetData row")){const values=[];for(const c of row.querySelectorAll("c")){const ref=c.getAttribute("r")||"A1",letters=ref.match(/[A-Z]+/)?.[0]||"A";let col=0;for(const x of letters)col=col*26+x.charCodeAt(0)-64;const type=c.getAttribute("t"),raw=c.querySelector("v")?.textContent??c.querySelector("is")?.textContent??"";values[col-1]=type==="s"?shared[+raw]??"":raw}matrix.push(values)}const rows=matrixToRows(matrix);if(rows.length)out.push({fileName,sheetName:s.getAttribute("name")||`Sheet ${si+1}`,rows})}return out}
async function inspectContainer(file){const ext=file.name.split(".").pop().toLowerCase();if(ext==="csv")return[{fileName:file.name,sheetName:"CSV",rows:parseCsv(await file.text())}];if(ext==="json")return jsonArrays(JSON.parse(await file.text())).map(x=>({...x,fileName:file.name}));if(ext==="xlsx")return workbookDatasets(file,file.name);if(ext!=="zip")throw Error(`Unsupported file: ${file.name}`);const entries=await unzip(file),out=[];for(const[name,item]of Object.entries(entries)){if(item.unsupported)continue;const e=name.split(".").pop().toLowerCase();try{if(e==="csv")out.push({fileName:name,sheetName:"CSV",rows:parseCsv(item.text())});else if(e==="json")out.push(...jsonArrays(JSON.parse(item.text())).map(x=>({...x,fileName:name})));else if(e==="xlsx")out.push(...await workbookDatasets(new Blob([item.data]),name))}catch(x){out.push({fileName:name,sheetName:"Unreadable",rows:[],error:x.message})}}return out}
async function uploadMarketplaceFiles(files){for(const file of files){try{const hash=await fingerprint(file);if(state.uploads.some(u=>u.fingerprint===hash)){toast(`${file.name} is already imported`,true);continue}const datasets=await inspectContainer(file),usable=datasets.filter(d=>d.rows.length),all=[],detectedTypes=[];for(const d of usable){const headers=Object.keys(d.rows[0]||{});if(!isMeeshoReport(headers))continue;const kind=/return/.test(d.fileName.toLowerCase())?"returns":"sales";detectedTypes.push(kind==="returns"?"Sales Returns / Credit Notes":"Sales");all.push(...normalizeMeeshoRows({rows:d.rows,fileName:d.fileName,sheetName:d.sheetName,kind}))}if(!all.length)throw Error("No Meesho transaction rows were found in the package");const checked=validateTransactions(all,{filingPeriod:state.setup[0].filingPeriod,existing:state.rows,supplierGstin:state.setup[0].gstin}),stats=importStatus(checked);for(const row of checked)await put("rows",row);await put("uploads",{id:uid("UP"),reportKey:"marketplace-package",fileName:file.name,fingerprint:hash,filesDetected:usable.length,rowCount:checked.length,marketplace:"Meesho",reportTypes:[...new Set(detectedTypes)].join(" + "),status:stats.error||stats.review||stats.warning?"Needs Review":"Ready",stats,createdAt:new Date().toISOString()});await load();render();toast(`${file.name}: ${stats.imported} actual Meesho rows parsed`)}catch(x){toast(`${file.name}: ${x.message}`,true)}}}
async function uploadFile(file,reportKey){if(!file)return;const ext=file.name.split(".").pop().toLowerCase();if(ext==="xls")return toast("Legacy binary .xls is not supported reliably. Save it as .xlsx or .csv.",true);let raw;try{if(ext==="csv")raw=parseCsv(await file.text());else if(ext==="json")raw=JSON.parse(await file.text());else if(ext==="xlsx")raw=await parseXlsx(file);else if(ext==="zip")raw=await parseUploadZip(file);else throw Error("Unsupported file type");if(!Array.isArray(raw))throw Error("Expected structured rows")}catch(x){return toast(x.message||"The structured file could not be read.",true)}if(!raw.length)return toast("The file contains no supported data rows.",true);pending={raw,file,reportKey,headers:Object.keys(raw[0])};mappingModal()}
async function unzip(file){const bytes=new Uint8Array(await file.arrayBuffer()),view=new DataView(bytes.buffer);let eocd=-1;for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error("Invalid ZIP/XLSX package");const count=view.getUint16(eocd+10,true),offset=view.getUint32(eocd+16,true),decoder=new TextDecoder(),files={};let pos=offset;for(let n=0;n<count;n++){if(view.getUint32(pos,true)!==0x02014b50)throw Error("Invalid ZIP directory");const method=view.getUint16(pos+10,true),size=view.getUint32(pos+20,true),nameLen=view.getUint16(pos+28,true),extra=view.getUint16(pos+30,true),comment=view.getUint16(pos+32,true),local=view.getUint32(pos+42,true),name=decoder.decode(bytes.slice(pos+46,pos+46+nameLen)),localName=view.getUint16(local+26,true),localExtra=view.getUint16(local+28,true),start=local+30+localName+localExtra,packed=bytes.slice(start,start+size);let data;if(method===0)data=packed;else if(method===8){const stream=new Blob([packed]).stream().pipeThrough(new DecompressionStream("deflate-raw"));data=new Uint8Array(await new Response(stream).arrayBuffer())}else{files[name]={unsupported:`compression method ${method}`};pos+=46+nameLen+extra+comment;continue}files[name]={data,text:()=>decoder.decode(data)};pos+=46+nameLen+extra+comment}return files}
async function parseUploadZip(file){const files=await unzip(file),supported=[],unsupported=[];for(const[name,item]of Object.entries(files)){if(item.unsupported){unsupported.push(`${name} (${item.unsupported})`);continue}const ext=name.split(".").pop().toLowerCase();try{if(ext==="csv")supported.push(...parseCsv(item.text()));else if(ext==="json"){const r=JSON.parse(item.text());if(Array.isArray(r))supported.push(...r);else unsupported.push(`${name} (JSON is not an array)`)}else unsupported.push(`${name} (unsupported entry)`)}catch{unsupported.push(`${name} (could not be parsed)`)}}if(unsupported.length)toast(`ZIP inspection: ${unsupported.join("; ")}`,true);if(!supported.length)throw Error("ZIP contains no supported CSV or row-array JSON files");return supported}
async function parseXlsx(file){const files=await unzip(file),sheet=files["xl/worksheets/sheet1.xml"];if(!sheet)throw Error("XLSX has no readable first worksheet");const parser=new DOMParser(),sharedFile=files["xl/sharedStrings.xml"],shared=sharedFile?[...parser.parseFromString(sharedFile.text(),"application/xml").querySelectorAll("si")].map(x=>x.textContent):[],xml=parser.parseFromString(sheet.text(),"application/xml"),matrix=[];for(const row of xml.querySelectorAll("sheetData row")){const values=[];for(const c of row.querySelectorAll("c")){const ref=c.getAttribute("r")||"A1",letters=ref.match(/[A-Z]+/)?.[0]||"A";let col=0;for(const x of letters)col=col*26+x.charCodeAt(0)-64;const type=c.getAttribute("t"),raw=c.querySelector("v")?.textContent??c.querySelector("is")?.textContent??"";values[col-1]=type==="s"?shared[+raw]??"":raw}matrix.push(values)}const headers=(matrix.shift()||[]).map(x=>String(x||"").trim());return matrix.filter(r=>r.some(x=>String(x||"").trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,String(r[i]??"").trim()]))) }
function mappingModal(){const aliases={invoiceNumber:["invoice no","invoice number","inv no"],invoiceDate:["invoice date","date"],buyerGstin:["gst no","gstin","buyer gstin"],placeOfSupply:["pos","place of supply"],taxableValue:["taxable amt","taxable value"],gstRate:["rate","gst rate"],cgst:["cgst","cgst amt"],sgst:["sgst","sgst amt"],igst:["igst","igst amt"],hsn:["hsn","hsn/sac"]};const option=(f)=>`<option value="">Not mapped</option>${pending.headers.map(h=>`<option ${aliases[f]?.includes(h.toLowerCase())?"selected":""}>${esc(h)}</option>`).join("")}`;modal("Review column mapping",`<p class="muted">Confirm mappings before import. The template can be reused for this source.</p><div class="mapping-grid">${FIELDS.map(f=>`<label class="mapping-row"><span>${label(f)}</span><select class="input" name="${f}">${option(f)}</select></label>`).join("")}</div><label>Mapping template name<input class="input" name="templateName" value="${esc(pending.file.name)}"></label>`,async v=>{const mapping={...v};delete mapping.templateName;await put("mappings",{id:uid("MAP"),name:v.templateName,reportKey:pending.reportKey,mapping,createdAt:new Date().toISOString()});const seen=new Set(state.rows.map(r=>`${r.documentType||'Invoice'}:${r.invoiceNumber}`));for(const source of pending.raw){const r={id:uid("ROW"),reportKey:pending.reportKey,sourceFile:pending.file.name,createdAt:new Date().toISOString()};for(const f of FIELDS)r[f]=mapping[f]?source[mapping[f]]:"";for(const f of["invoiceValue","taxableValue","gstRate","cgst","sgst","igst","cess","quantity"])r[f]=r[f]===""?"":+String(r[f]).replaceAll(",","");if(!r.documentType)r.documentType=pending.reportKey.includes("return")||pending.reportKey==="notes"?"Credit Note":"Invoice";if(!r.source&&state.setup[0].businessType==="E-commerce Seller")r.source=pending.reportKey.split("-")[0];r.section9_5=state.setup[0].section9_5;const validation=validateRow(r,{seen,ecommerce:state.setup[0].businessType==="E-commerce Seller"});r.validation=validation;seen.add(`${r.documentType}:${r.invoiceNumber}`);await put("rows",r)}await put("uploads",{id:uid("UP"),reportKey:pending.reportKey,fileName:pending.file.name,rowCount:pending.raw.length,createdAt:new Date().toISOString()});pending=null},"Import & Validate")}
function label(f){return f.replace(/([A-Z])/g," $1").replace(/^./,x=>x.toUpperCase())}
function modal(title,body,save,labelText="Save"){$("#gst-modal").innerHTML=`<div class="modal-bg"><section class="modal"><form id="modal-form"><header><h2>${title}</h2><button type="button" class="btn secondary" data-close>Close</button></header><div class="modal-body">${body}</div><footer>${btn(labelText,"","primary")}</footer></form></section></div>`;$("[data-close]").onclick=()=>$("#gst-modal").innerHTML="";$("#modal-form").onsubmit=async e=>{e.preventDefault();try{await save(Object.fromEntries(new FormData(e.target)));$("#gst-modal").innerHTML="";await load();render();toast("Saved and validated")}catch(x){toast(x.message,true)}}}
function changeBusinessDialog(){$("#gst-modal").innerHTML=`<div class="modal-bg"><section class="modal confirm-modal" role="dialog" aria-modal="true" aria-labelledby="change-business-title" aria-describedby="change-business-description"><header><h2 id="change-business-title">Change business setup?</h2></header><div class="modal-body"><p id="change-business-description">You will return to the GST setup screen and can choose your business type again.</p></div><footer><button type="button" class="btn secondary" data-cancel-change>Cancel</button><button type="button" class="btn primary" data-confirm-change>Change Business</button></footer></section></div>`;$("[data-cancel-change]").onclick=()=>$("#gst-modal").innerHTML="";$("[data-confirm-change]").onclick=async()=>{try{await clearActiveWorkspace();pending=null;view="gstr1";$("#gst-modal").innerHTML="";await load();render()}catch(x){toast(x.message,true)}}}
function correct(id){const r=state.rows.find(x=>x.id===id);modal("Correct tax row",`<div class="form-grid">${["marketplace","invoiceNumber","orderId","invoiceDate","documentType","reference","buyerGstin","placeOfSupply","stateCode","taxableValue","gstRate","cgst","sgst","igst","cess","hsn","ecoGstin"].map(f=>`<label>${label(f)}<input class="input" name="${f}" value="${esc(r[f])}" ${f==="invoiceDate"?'type="date"':""}></label>`).join("")}</div>`,async v=>{const updated={...r,...v,source:v.marketplace};for(const f of["taxableValue","gstRate","cgst","sgst","igst","cess"])updated[f]=v[f]===""?null:+v[f];if(state.setup[0].businessType==="E-commerce Seller")updated.validation=validateTransactions([updated],{filingPeriod:state.setup[0].filingPeriod,existing:state.rows.filter(x=>x.id!==id)})[0].validation;else updated.validation=validateRow(updated,{seen:new Set(state.rows.filter(x=>x.id!==id).map(x=>`${x.documentType||'Invoice'}:${x.invoiceNumber}`)),ecommerce:false});await put("rows",updated)})}
function dl(name,text,type="application/json"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJson(){if(state.setup[0].businessType==="E-commerce Seller"){try{const json=gstr1Json(state.rows,state.setup[0]);return dl(`gstr1-${state.setup[0].gstin}-${state.setup[0].filingPeriod}.json`,JSON.stringify(json,null,2))}catch(x){return toast(x.message,true)}}const stats=countStats(state.rows);if(stats.errors)return toast("Resolve or exclude critical errors before generating preparation JSON.",true);const sum=summaries(state.rows);dl("infobridgeindia-gstr1-preparation.json",JSON.stringify({format:"InfoBridgeIndia GST Preparation JSON",portalUploadCompatible:false,warning:"Not for direct GST Portal upload",gstin:state.setup[0].gstin,generatedAt:new Date().toISOString(),groups:sum.groups,hsnSummary:sum.hsn,documentSummary:sum.documents},null,2))}
function exportReview(){if(state.setup[0].businessType==="E-commerce Seller"){const s=consolidate(state.rows),total=a=>a.reduce((n,r)=>n+(r.taxableValue||0),0),sheets={"Filing Summary":[{GSTIN:state.setup[0].gstin,"Filing Period":state.setup[0].filingPeriod,Marketplaces:[...new Set(s.active.map(r=>r.marketplace))].join(", "),Transactions:s.active.length,"Sales Rows":s.active.filter(r=>r.documentType==="Invoice").length,"Return Rows":s.notes.filter(r=>r.documentType==="Credit Note").length,"Sales Taxable Value":total(s.active.filter(r=>r.documentType==="Invoice")),"Return Adjustment":total(s.notes.filter(r=>r.documentType==="Credit Note")),"Final Taxable Value":total(s.active),IGST:s.active.reduce((n,r)=>n+r.igst,0),CGST:s.active.reduce((n,r)=>n+r.cgst,0),SGST:s.active.reduce((n,r)=>n+r.sgst,0),Cess:s.active.reduce((n,r)=>n+r.cess,0)}],B2B:s.b2b,B2C:s.b2c,"Credit Debit Notes":s.notes,"HSN SAC":s.hsn,"Nil Exempt Non GST":[...s.nil.map(r=>({...r,Category:"Nil-rated"})),...s.exempt.map(r=>({...r,Category:"Exempt"})),...s.nonGst.map(r=>({...r,Category:"Non-GST"}))],"E-commerce":s.eco,"Documents Issued":s.documents,"Validation Needs Review":state.rows.filter(r=>r.validation?.severity!=="Valid"||r.duplicate),"Source Reconciliation":state.rows.map(r=>({Marketplace:r.marketplace,"Source File":r.sourceFile,"Source Sheet":r.sourceSheet,"Source Row":r.sourceRow,"Order ID":r.orderId,"Invoice Number":r.invoiceNumber,Outcome:r.excluded?"Excluded":r.duplicate?"Duplicate":r.validation?.severity}))};if(!s.b2b.length)delete sheets.B2B;if(!s.nil.length&&!s.exempt.length&&!s.nonGst.length)delete sheets["Nil Exempt Non GST"];if(!s.documents.length){delete sheets["Documents Issued"];sheets["Validation Needs Review"].push({Severity:"Needs Review",Field:"Documents Issued",Problem:"Invoice/credit-note series is not available in the Meesho package",Action:"Confirm document series before filing-ready JSON"})}return dl(`gstr1-review-${state.setup[0].gstin}-${state.setup[0].filingPeriod}.xls`,spreadsheetXml(sheets),"application/vnd.ms-excel")}const sum=summaries(state.rows),sheets={Summary:Object.entries(sum.groups).map(([group,rows])=>({Group:group,Rows:rows.length,"Taxable Value":rows.reduce((a,r)=>a+(+r.taxableValue||0),0)})),B2B:sum.groups.B2B,B2C:sum.groups.B2C,"Credit Debit Notes":sum.groups["Credit / Debit Notes"],Exports:sum.groups.Exports,"E-commerce":sum.groups["E-commerce"],"HSN Summary":sum.hsn,"Document Summary":sum.documents,"Errors Warnings":state.rows.filter(r=>r.validation.severity!=="Valid")};dl("gstr1-review-workbook.xls",spreadsheetXml(sheets),"application/vnd.ms-excel")}
function spreadsheetXml(sheets){return`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Header"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#0D7C68" ss:Pattern="Solid"/></Style></Styles>${Object.entries(sheets).map(([name,rows])=>{const headers=[...new Set(rows.flatMap(Object.keys))];return`<Worksheet ss:Name="${esc(name).slice(0,31)}"><Table><Row>${headers.map(h=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${esc(label(h))}</Data></Cell>`).join("")}</Row>${rows.map(r=>`<Row>${headers.map(h=>`<Cell><Data ss:Type="${typeof r[h]==='number'?'Number':'String'}">${esc(typeof r[h]==='object'?JSON.stringify(r[h]):r[h])}</Data></Cell>`).join("")}</Row>`).join("")}</Table></Worksheet>`}).join("")}</Workbook>`}
async function backup(){dl("infobridgeindia-gst-workspace-backup.json",JSON.stringify({schema:DB,version:1,exportedAt:new Date().toISOString(),stores:Object.fromEntries(STORES.map(s=>[s,state[s]]))},null,2))}async function restore(e){try{const x=JSON.parse(await e.target.files[0].text());if(x.schema!==DB||!x.stores?.setup?.[0]?.gstin||!Array.isArray(x.stores.rows))throw Error("Invalid GST workspace backup");if(!confirm("Replace all current GST workspace data with this backup?"))return;for(const s of STORES)await store.replace(s,x.stores[s]||[]);await load();render();toast("GST workspace restored")}catch(x){toast(x.message,true)}}
await openDb();await load();render();
